'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import AppLayout from '@/components/AppLayout';
import SearchableSelect from '@/components/SearchableSelect';
import VoucherDetails from '@/components/VoucherDetails';
import {createClient} from '@/lib/supabase/client';
import {useAuth} from '@/contexts/AuthContext';
import {useRealtimeTable} from '@/lib/hooks/useRealtimeTable';
type Row=Record<string,any>;
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(n);
const types:Record<string,string>={payment:'Payment / Advance paid',opening_due:'Opening amount payable',opening_advance:'Opening advance paid',refund:'Refund received'};
const dueEffect=(p:Row)=>['payment','opening_advance'].includes(p.entry_type)?-Number(p.amount):Number(p.amount);
function Accounts(){
 const {can}=useAuth();const [data,setData]=useState<{parties:Row[];work:Row[];payments:Row[];history:Row[]}>({parties:[],work:[],payments:[],history:[]});
 const [error,setError]=useState(''),[loading,setLoading]=useState(true),[kind,setKind]=useState('operator'),[party,setParty]=useState(''),[modal,setModal]=useState<Row|null>(null),[rateRow,setRateRow]=useState<Row|null>(null),[rate,setRate]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const saving=useRef(false),generation=useRef(0);
 const load=useCallback(async()=>{const g=++generation.current;try{const {data,error}=await createClient().rpc('erp_work_accounts');if(error)throw error;if(g===generation.current){setData(data);setError('');}}catch(e){if(g===generation.current)setError((e as Error).message);}finally{if(g===generation.current)setLoading(false);}},[]);
 useEffect(()=>{void load();return()=>{generation.current++;};},[load]);
 useRealtimeTable('erp_work_payments',load);
 const work=data.work.filter(r=>r.kind===kind&&(!party||r.party_id===party));const payments=data.payments.filter(r=>r.kind===kind&&(!party||r.party_id===party));
 const active=payments.filter(p=>!p.voided),missing=work.filter(r=>r.amount==null),unlinked=data.work.filter(r=>r.kind===kind&&!r.party_id);
 const earned=work.reduce((s,r)=>s+Number(r.amount||0),0),paid=active.filter(p=>['payment','opening_advance'].includes(p.entry_type)).reduce((s,p)=>s+Number(p.amount),0),due=earned+active.reduce((s,p)=>s+dueEffect(p),0);
 const partyName=(r:Row)=>data.parties.find(p=>p.kind===r.kind&&p.id===r.party_id)?.name||r.party_name||'Master link missing';
 function newPayment(){if(!party)return;setNotice('');setError('');setModal({id:crypto.randomUUID(),entry_date:new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata'}).format(new Date()),entry_type:'payment',amount:'',method:'Bank',reference:'',remarks:'',revision:0,kind,party_id:party});}
 async function mutation(fn:()=>Promise<void>){if(saving.current)return;saving.current=true;setBusy(true);setError('');try{await fn();await load();}catch(e){setError((e as Error).message);}finally{saving.current=false;setBusy(false);}}
 async function savePayment(){if(!modal)return;await mutation(async()=>{const {data,error}=await createClient().rpc('erp_save_work_payment',{p_id:modal.id,p_kind:modal.kind,p_party:modal.party_id,p_date:modal.entry_date,p_type:modal.entry_type,p_amount:modal.amount===''?null:Number(modal.amount),p_method:modal.method,p_reference:modal.reference,p_remarks:modal.remarks,p_revision:modal.revision});if(error)throw error;if(data?.id!==modal.id)throw Error('Could not confirm saved payment. Refresh before retrying.');setModal(null);setNotice('Payment entry saved.');});}
 async function saveRate(){if(!rateRow)return;await mutation(async()=>{const {error}=await createClient().rpc('erp_set_contractor_account_rate',{p_item:rateRow.source_key.slice('contractor:'.length),p_rate:rate===''?null:Number(rate),p_revision:rateRow.rate_revision});if(error)throw error;setRateRow(null);setNotice('Rate saved; received quantity amount updated.');});}
 const ledger:Row[]=[...work.map(r=>({...r,entry_date:r.entry_date,label:r.voucher_no,change:r.amount==null?null:Number(r.amount),category:'work'})),...active.map(p=>({...p,label:types[p.entry_type],change:dueEffect(p),category:'payment'}))].sort((a:Row,b:Row)=>String(a.entry_date).localeCompare(String(b.entry_date))||String(a.source_key||a.id).localeCompare(String(b.source_key||b.id)));
 let running=0;
 return <div className="space-y-5"><div className="flex flex-wrap gap-3 justify-between"><div><h1 className="text-xl font-bold">Production Accounts</h1><p className="text-sm text-muted-foreground">Received work, payments, advances and outstanding amounts.</p></div><button className="btn-secondary" disabled={busy} onClick={()=>void load()}>Refresh</button></div>
 {error&&<p role="alert" className="text-red-700 border border-red-200 p-3 rounded">{error}</p>}{notice&&<p role="status" className="text-green-700">{notice}</p>}
 <div className="flex flex-wrap gap-3"><SearchableSelect aria-label="Master category" value={kind} onChange={e=>{setKind(e.target.value);setParty('');}} className="input-field"><option value="operator">Operators</option><option value="cutting">Cutting Masters</option><option value="contractor">Contractors / Accounts</option></SearchableSelect><SearchableSelect aria-label="Select account" value={party} onChange={e=>setParty(e.target.value)} className="input-field flex-1 min-w-[200px]"><option value="">All accounts</option>{data.parties.filter(p=>p.kind===kind).sort((a,b)=>String(a.name).localeCompare(String(b.name))).map(p=><option key={p.id} value={p.id}>{p.name} {p.code?`· ${p.code}`:''} · {p.id.slice(0,8)}</option>)}</SearchableSelect>{can('work_accounts','create')&&<button className="btn-primary" disabled={!party||loading||!!error} onClick={newPayment}>Record payment / opening balance</button>}</div>
 {loading?<p>Loading accounts…</p>:<><div className="grid grid-cols-1 sm:grid-cols-3 gap-3">{[['Received work amount',earned],['Payments / advances',paid],[due<0?'Advance balance':'Amount payable',Math.abs(due)]].map(([label,value])=><div key={String(label)} className="border rounded-xl p-4"><p className="text-sm">{label}{missing.length?' (incomplete)':''}</p><p className="text-xl font-bold">{money(Number(value))}</p></div>)}</div>
 {(missing.length>0||unlinked.length>0)&&<p role="alert" className="p-3 rounded bg-amber-50 text-amber-900">{missing.length} receipt lines need rates / charge quantities; {unlinked.length} lines need a unique master link. Totals exclude unpriced work. Review these before settling an account.</p>}
 <p className="text-xs text-muted-foreground">Stitching uses received pieces and the Job Card rate. Cutting uses net accepted pieces, or the component’s recorded charge metres for per-metre work. Embroidery/Handwork use the accepted receive quantity and recorded rate or fixed charge. Contractor rates are entered against received component lines.</p>
 <div className="overflow-x-auto border rounded-xl"><table className="w-full min-w-[950px] text-sm"><thead><tr className="bg-slate-50 text-left">{['Date','Account','Voucher / Entry','Job / Item / Component','Received / Charge Qty','Rate','Amount (+ due / − paid)','Running balance','Actions'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{ledger.map(r=>{running=Math.round((running+Number(r.change||0))*100)/100;return <tr className="border-t" key={r.source_key||r.id}><td className="p-3">{r.entry_date}</td><td className="p-3">{partyName(r)}</td><td className="p-3">{r.category==='work'?<VoucherDetails table={r.source_table} recordId={r.source_id} label={r.voucher_no}/>:<span>{r.label}<br/><small>{r.reference} · {r.method}</small></span>}</td><td className="p-3">{r.job_card_ref}<br/>{r.item_name}<br/>{r.component||r.remarks}</td><td className="p-3">{r.category==='work'?`${r.quantity??'Missing'} ${r.unit}`:'—'}</td><td className="p-3">{r.category==='work'?(r.rate!=null?money(Number(r.rate)):r.fixed_amount!=null?'Fixed charge':'Rate pending'):'—'}</td><td className="p-3">{r.change==null?'Rate pending':money(r.change)}</td><td className="p-3">{money(running)}{missing.length?' *':''}</td><td className="p-3">{r.category==='work'?(r.source_key?.startsWith('contractor:')&&can('work_accounts','edit')?<button className="text-primary underline" onClick={()=>{setRateRow(r);setRate(r.rate==null?'':String(r.rate));}}>Set rate</button>:r.source_table==='stitch_receive_vouchers'?<Link href="/job-card-management" className="text-primary underline">Job Card rates</Link>:null):<div className="flex gap-2">{can('work_accounts','edit')&&<button className="text-primary underline" onClick={()=>setModal({...r})}>Edit</button>}{can('work_accounts','delete')&&<button className="text-red-700 underline" onClick={()=>{const reason=window.prompt('Reason for voiding this payment entry:');if(reason?.trim())void mutation(async()=>{const {error}=await createClient().rpc('erp_void_work_payment',{p_id:r.id,p_revision:r.revision,p_reason:reason});if(error)throw error;});}}>Void</button>}</div>}</td></tr>})}{!ledger.length&&<tr><td colSpan={9} className="p-6 text-center">No received work or payment entries for this selection.</td></tr>}</tbody></table></div>
 <details className="border rounded-xl p-3"><summary>Voided payments and change history</summary>{payments.filter(p=>p.voided).map(p=><p key={p.id} className="text-sm my-2">{p.entry_date} · {partyName(p)} · {money(Number(p.amount))} · Voided</p>)}{data.history.filter(h=>h.record_type==='rate'?work.some(w=>w.source_key==='contractor:'+h.record_id):payments.some(p=>p.id===h.record_id)).map(h=><details key={h.id} className="text-xs border-t p-2"><summary>{h.changed_at} · {h.record_type} · {h.actor}</summary><pre className="whitespace-pre-wrap">{JSON.stringify({before:h.old_data,after:h.new_data},null,2)}</pre></details>)}</details></>}
 {(modal||rateRow)&&<div className="fixed inset-0 z-50 bg-black/40 p-4 flex items-center justify-center"><section role="dialog" aria-modal="true" aria-label={modal?'Payment entry':'Contractor received rate'} className="bg-white rounded-xl p-5 w-full max-w-lg max-h-[90vh] overflow-auto"><h2 className="font-bold mb-3">{modal?'Payment / Opening Balance':'Contractor Rate · '+rateRow?.voucher_no}</h2>{error&&<p role="alert" className="text-red-700 mb-3">{error}</p>}{modal?<form onSubmit={e=>{e.preventDefault();void savePayment();}} className="space-y-3"><p>{partyName(modal)}</p><label className="block">Date<input required type="date" value={modal.entry_date} onChange={e=>setModal({...modal,entry_date:e.target.value})} className="input-field w-full"/></label><label className="block">Entry type<SearchableSelect value={modal.entry_type} onChange={e=>setModal({...modal,entry_type:e.target.value})} className="input-field w-full">{Object.entries(types).map(([k,v])=><option key={k} value={k}>{v}</option>)}</SearchableSelect></label><label className="block">Amount ₹<input required type="number" min="0.01" step="0.01" value={modal.amount} onChange={e=>setModal({...modal,amount:e.target.value})} className="input-field w-full"/></label>{['method','reference','remarks'].map(key=><label key={key} className="block capitalize">{key}<input value={modal[key]} onChange={e=>setModal({...modal,[key]:e.target.value})} className="input-field w-full"/></label>)}<p className="text-xs">This records a payment already made; it does not transfer money.</p><div className="flex gap-3"><button disabled={busy} type="button" className="btn-secondary" onClick={()=>setModal(null)}>Cancel</button><button disabled={busy} className="btn-primary">{busy?'Saving…':'Save entry'}</button></div></form>:<form onSubmit={e=>{e.preventDefault();void saveRate();}} className="space-y-3"><p>{rateRow?.component} · Received {rateRow?.quantity} {rateRow?.unit}</p><label className="block">Rate ₹ / received piece<input required type="number" min="0" step="0.01" value={rate} onChange={e=>setRate(e.target.value)} className="input-field w-full"/></label><p>Amount: {rate===''?'Rate pending':money(Number(rate)*Number(rateRow?.quantity))}</p><div className="flex gap-3"><button type="button" disabled={busy} className="btn-secondary" onClick={()=>setRateRow(null)}>Cancel</button><button disabled={busy} className="btn-primary">Save rate</button></div></form>}</section></div>}
 </div>;
}
export default function Page(){return <AppLayout pageTitle="Production Accounts" pageTitleHi="उत्पादन लेखा" render={()=> <Accounts/>}/>;}
