'use client';
import SearchableSelect from '@/components/SearchableSelect';

import {useEffect,useState} from 'react';
import {X} from 'lucide-react';
import {FabricStockItem} from '../data/fabricStockData';
import {fabricInventoryService,type FabricVoucherEdit} from '@/lib/services/fabricInventoryService';
import {VoucherDetailPanel} from '@/components/VoucherDetails';
import {supabase} from '@/lib/supabase/client';
import {useAuth} from '@/contexts/AuthContext';
import {erpErrorMessage} from '@/lib/erpError';
type Props={fabricName:string;entries:FabricStockItem[];loading:boolean;onClose:()=>void;error?:string};
function Shell({title,onClose,children,busy=false}:{title:string;onClose:()=>void;children:React.ReactNode;busy?:boolean}){return <div className="erp-modal-enter fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-3" role="dialog" aria-modal="true" aria-label={title}><section className="bg-card rounded-2xl w-full max-w-3xl max-h-[90dvh] flex flex-col shadow-xl"><header className="p-4 flex justify-between gap-3 border-b"><h2 className="font-bold">{title}</h2><button type="button" disabled={busy} aria-label="Close" onClick={onClose}><X size={20}/></button></header><div className="overflow-auto p-4 sm:p-6">{children}</div></section></div>;}
export function ViewModal({fabricName,entries,loading,onClose,error}:Props){const [selected,setSelected]=useState('');return <Shell title={fabricName+' · Voucher entries'} onClose={onClose}>{loading?<p role="status">Loading entries…</p>:error?<p role="alert">{error}</p>:<div className="space-y-4">{!entries.length&&<p>No entries found.</p>}{entries.map((entry,i)=><section key={entry.id} className="border rounded-xl p-3"><button type="button" className="flex w-full justify-between gap-2 text-left font-semibold" aria-expanded={(selected||entries[0]?.id)===entry.id} onClick={()=>setSelected(selected===entry.id?'closed':entry.id)}><span>{entry.voucherNo||`Entry ${i+1} · voucher number not recorded`} {entry.rollNo?`/ ${entry.rollNo}`:''}</span><span>{entry.stockQty.toFixed(2)} {entry.unit}</span></button>{(selected||entries[0]?.id)===entry.id&&<div className="mt-4"><VoucherDetailPanel table="fabric_inventory" recordId={entry.id}/></div>}</section>)}</div>}</Shell>;}
function EntryEditor({entry,saving,onSave}:{entry:FabricStockItem;saving:boolean;onSave:(id:string,values:FabricVoucherEdit)=>Promise<void>}){
 const {can}=useAuth();const [checking,setChecking]=useState(true),[lock,setLock]=useState(''),[error,setError]=useState(''),[jobs,setJobs]=useState<{id:string;job_card_no:string}[]>([]);
 const [v,setV]=useState<FabricVoucherEdit>({fabricName:entry.fabricName,category:entry.category,categoryLabel:entry.categoryLabel||entry.category,stockQty:entry.stockQty,unit:entry.unit,voucherNo:entry.voucherNo||'',voucherDate:entry.voucherDate||entry.receivedDate||'',source:entry.entrySource||'',remarks:entry.remarks||'',rollNo:entry.rollNo||'',width:entry.fabricWidth||'',jobCardId:entry.jobCardId||null,updatedAt:entry.updatedAt||null});
 useEffect(()=>{let alive=true;void (async()=>{try{const {data,error}=await supabase.rpc('erp_voucher_detail',{p_table:'fabric_inventory',p_record_id:entry.id});if(error)throw error;if(alive)setLock(data.lock_reason||((entry.sourceModule&&entry.sourceModule!=='manual')||entry.sourceReceiptId?'This stock comes from a processing receipt. View its Source voucher; derived stock cannot be edited independently.':''));if(can('jobs')){const r=await supabase.from('job_cards').select('id,job_card_no').order('job_card_no');if(r.error)throw r.error;if(alive)setJobs(r.data||[]);}}catch(e){if(alive)setError(erpErrorMessage(e));}finally{if(alive)setChecking(false);}})();return()=>{alive=false};},[entry.id]);
 const field=(key:keyof FabricVoucherEdit,label:string,type='text',required=false)=><label className="space-y-1 text-sm" key={key}><span>{label}{required?' *':''}</span><input className="input-field w-full" type={type} required={required} min={type==='number'?'0.01':undefined} step={type==='number'?'any':undefined} value={String(v[key]??'')} onChange={e=>setV(old=>({...old,[key]:type==='number'?e.target.value:e.target.value}))}/></label>;
 if(checking)return <p role="status">Checking voucher links and edit access…</p>;
 return <div className="space-y-4">{lock?<><p className="border border-amber-300 bg-amber-50 text-amber-900 p-3 rounded-lg">{lock}</p><VoucherDetailPanel table="fabric_inventory" recordId={entry.id}/></>:<form onSubmit={async e=>{e.preventDefault();if(saving||error)return;try{await onSave(entry.id,{...v,stockQty:Number(v.stockQty)});}catch(e){setError(erpErrorMessage(e));}}}><fieldset disabled={saving||!can('fabric','edit')} className="grid grid-cols-1 sm:grid-cols-2 gap-4">{field('voucherNo','Voucher number','text',true)}{field('voucherDate','Voucher date','date',true)}{field('fabricName','Fabric name','text',true)}{field('categoryLabel','Fabric category / quality','text',true)}<label className="text-sm">Stock category<SearchableSelect className="input-field w-full" value={v.category} onChange={e=>setV({...v,category:e.target.value})}>{['JK','MALMAL','RAYON','YUFTA','KERI_PRINT','OTHER'].map(c=><option key={c}>{c}</option>)}</SearchableSelect></label><label className="text-sm">Unit<SearchableSelect className="input-field w-full" value={v.unit} onChange={e=>setV({...v,unit:e.target.value})}>{['Metre','Metres','Yard','KG','Pcs'].map(c=><option key={c}>{c}</option>)}</SearchableSelect></label>{field('stockQty','Quantity','number',true)}{field('rollNo','Roll number')}{field('width','Fabric width')}{field('source','Source / supplier')}{field('remarks','Remarks')}<label className="text-sm">Job Card (optional)<SearchableSelect className="input-field w-full" disabled={!can('jobs')} value={v.jobCardId||''} onChange={e=>setV({...v,jobCardId:e.target.value||null})}><option value="">Not linked</option>{entry.jobCardId&&!jobs.some(j=>j.id===entry.jobCardId)&&<option value={entry.jobCardId}>Existing Job Card (details restricted)</option>}{jobs.map(j=><option key={j.id} value={j.id}>{j.job_card_no}</option>)}</SearchableSelect></label><button type="submit" disabled={!!error} className="btn-primary sm:col-span-2">{saving?'Saving…':'Save changes'}</button></fieldset></form>}{error&&<div role="alert" className="text-red-700">{error}<button type="button" className="underline ml-2" onClick={()=>setError('')}>Dismiss</button></div>}</div>;
}
export function EditModal({fabricName,entries,loading,saving,onSave,onClose,error}:Props&{saving:boolean;onSave:(id:string,v:FabricVoucherEdit)=>Promise<void>}){const [id,setId]=useState('');const entry=entries.find(e=>e.id===id)||entries[0];return <Shell title={'Edit fabric voucher · '+fabricName} onClose={onClose} busy={saving}>{loading?<p role="status">Loading entries…</p>:error?<p role="alert">{error}</p>:entry?<><label className="text-sm">Select voucher / roll<SearchableSelect className="input-field w-full mb-4" disabled={saving} value={entry.id} onChange={e=>setId(e.target.value)}>{entries.map((e,i)=><option value={e.id} key={e.id}>{e.voucherNo||`Legacy entry ${i+1}`} · {e.rollNo||'Roll not recorded'} · {e.stockQty} {e.unit}</option>)}</SearchableSelect></label><EntryEditor key={entry.id+entry.updatedAt} entry={entry} saving={saving} onSave={onSave}/></>:<p>No entries found.</p>}</Shell>;}
