const fs=require('fs'),assert=require('node:assert/strict');
const {PGlite}=require('@electric-sql/pglite');
(async()=>{
 const db=new PGlite();
 await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE SCHEMA auth;
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 CREATE TABLE public.job_cards(id uuid PRIMARY KEY,job_card_no text,protected boolean default false);
 CREATE TABLE public.sales_orders(id uuid PRIMARY KEY,vch_no text);
 GRANT USAGE ON SCHEMA public,auth TO anon,authenticated;
 GRANT ALL ON public.job_cards,public.sales_orders TO anon,authenticated;
 ALTER TABLE job_cards ENABLE ROW LEVEL SECURITY; ALTER TABLE sales_orders ENABLE ROW LEVEL SECURITY;
 CREATE POLICY legacy ON job_cards FOR ALL TO anon,authenticated USING(true) WITH CHECK(true);
 CREATE POLICY legacy ON sales_orders FOR ALL TO anon,authenticated USING(true) WITH CHECK(true);
 CREATE POLICY user_delete ON job_cards AS RESTRICTIVE FOR DELETE TO authenticated USING(NOT protected);
 INSERT INTO job_cards VALUES ('11111111-1111-1111-1111-111111111111','JC-1',false),('22222222-2222-2222-2222-222222222222','JC-protected',true);
 INSERT INTO sales_orders VALUES ('33333333-3333-3333-3333-333333333333','PO-1');`);
 const sql=fs.readFileSync('safety-update/DELETE-SAFETY.sql','utf8');await db.exec(sql);await db.exec(sql);
 await db.exec('SET ROLE anon');
 assert.equal((await db.query('SELECT * FROM job_cards')).rows.length,0);
 assert.equal((await db.query('DELETE FROM sales_orders RETURNING id')).rows.length,0);
 await assert.rejects(()=>db.exec("INSERT INTO job_cards(id) VALUES('44444444-4444-4444-4444-444444444444')"));
 await db.exec("RESET ROLE; SET ROLE authenticated; SET request.jwt.claim.sub='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'; SET request.method='DELETE'; SET request.path='/job_cards'; SET request.headers='{\"x-client-info\":\"rangraahi-delete-v1;screen=job-card-management\",\"authorization\":\"DO-NOT-LOG\"}'");
 assert.equal((await db.query('SELECT * FROM job_cards')).rows.length,2);
 assert.equal((await db.query('DELETE FROM job_cards WHERE protected RETURNING id')).rows.length,0);
 await db.exec('BEGIN; DELETE FROM job_cards WHERE NOT protected; ROLLBACK; RESET ROLE');
 assert.equal((await db.query('SELECT * FROM erp_delete_request_audit')).rows.length,0);
 await db.exec('SET ROLE authenticated; DELETE FROM job_cards WHERE NOT protected');
 await assert.rejects(()=>db.query('SELECT * FROM erp_delete_request_audit'));
 await db.exec('RESET ROLE');const logs=(await db.query('SELECT * FROM erp_delete_request_audit')).rows;
 assert.equal(logs.length,1);assert.equal(logs[0].actor_id,'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa');assert.equal(logs[0].record_reference,'JC-1');assert.equal(logs[0].request_method,'DELETE');assert.equal(logs[0].database_role,'authenticated');assert.ok(!JSON.stringify(logs).includes('DO-NOT-LOG'));
 console.log('PASS: anonymous access blocked; authenticated view/delete restrictions preserved; exact deletion context recorded privately; rollback leaves no false deletion log; migration reruns safely');
 await db.close();
})();
