const fs=require('fs'),vm=require('vm'),assert=require('assert'),ts=require('typescript');
const React=require('/tmp/erp-form-tests/node_modules/react');const {create,act}=require('/tmp/erp-form-tests/node_modules/react-test-renderer');global.IS_REACT_ACT_ENVIRONMENT=true;
let callback,pending,hold=false,ctx,mounts=0;let profile={user_id:'a',active:true};const session={user:{id:'a'}};
const supabase={auth:{onAuthStateChange(cb){callback=cb;return {data:{subscription:{unsubscribe(){}}}}},async getSession(){return {data:{session}}},getUser(){return hold?new Promise(r=>pending=r):Promise.resolve({data:{user:{id:'a'}}})}},from(){return {select(){return this},eq(){return this},async maybeSingle(){return {data:{...profile}}}}}};
function load(file,mocks){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,require:n=>mocks[n]||require(n),console:{log(){}},setTimeout,clearTimeout,setInterval:()=>1,clearInterval(){},window:{addEventListener(){},removeEventListener(){}},document:{visibilityState:'visible',addEventListener(){},removeEventListener(){}}});return exports}
const mod=load('src/contexts/AuthContext.tsx',{'react':React,'react/jsx-runtime':require('/tmp/erp-form-tests/node_modules/react/jsx-runtime'),'@/lib/supabase/client':{supabase},'@/lib/moduleAccess':{routeAllowed:()=>true,hasPermission:p=>!!p?.active}});
function Form(){const [v,set]=React.useState('');React.useEffect(()=>{mounts++},[]);return React.createElement('input',{value:v,onChange:set})}function Gate(){ctx=mod.useAuth();return !ctx.loading&&!ctx.accessLoading&&ctx.sessionStatus==='signed-in'?React.createElement(Form):null}
const tick=()=>new Promise(r=>setTimeout(r,10));
(async()=>{let root;await act(async()=>{root=create(React.createElement(mod.AuthProvider,null,React.createElement(Gate)))});await act(tick);await act(async()=>root.root.findByType('input').props.onChange('unsaved voucher'));
const can=ctx.can;hold=true;await act(async()=>{callback('TOKEN_REFRESHED',session);await tick()});assert.equal(root.root.findByType('input').props.value,'unsaved voucher');assert.equal(mounts,1);
await act(async()=>{pending({data:{user:{id:'a'}}});await tick()});await act(async()=>ctx.refreshAccess());assert.strictEqual(ctx.can,can);assert.equal(mounts,1);
await act(async()=>{callback('SIGNED_IN',session);await tick()});assert.equal(root.root.findByType('input').props.value,'unsaved voucher');
await act(async()=>{profile.active=false;await ctx.refreshAccess()});assert.equal(ctx.can('items'),false);
await act(async()=>callback('SIGNED_OUT',null));assert.equal(root.root.findAllByType('input').length,0);await act(async()=>root.unmount());console.log('PASS: same-user refresh preserves form, permissions refresh stays stable, revoked permissions and logout enforced');
let flags=[];const ex={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/erpFetch.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports:ex,require:n=>n.includes('requestProgress')?{beginRequest:w=>{flags.push(w);return()=>{}}}:{erpErrorMessage:String},window:{location:{pathname:'/'}},URL,Request,fetch:async()=>({ok:true})});for(const rpc of ['erp_order_linked_report','erp_job_reporting','erp_list_users'])await ex.erpFetch('https://example.com/rest/v1/rpc/'+rpc,{method:'POST'});await ex.erpFetch('https://example.com/rest/v1/vouchers',{method:'POST'});assert.deepEqual(flags,[false,false,false,true]);console.log('PASS: background reports are reads; voucher save remains a write');})().catch(e=>{console.error(e);process.exitCode=1});
