const {PGlite}=require('@electric-sql/pglite'),fs=require('fs'),assert=require('node:assert/strict');
(async()=>{const db=new PGlite();try{
await db.exec(fs.readFileSync('verification/team-schema-fixture.sql','utf8'));
await db.exec(`ALTER TABLE erp_user_access ADD COLUMN IF NOT EXISTS is_owner boolean;
INSERT INTO erp_user_access(user_id,display_name,active,is_owner) VALUES('00000000-0000-0000-0000-000000000001','Owner',true,true);
SET request.jwt.claim.sub='00000000-0000-0000-0000-000000000001';
CREATE TABLE test_locks(table_name text,id text);CREATE FUNCTION erp_is_voucher_locked(text,text) RETURNS boolean LANGUAGE sql AS $$SELECT EXISTS(SELECT 1 FROM test_locks WHERE table_name=$1 AND id=$2)$$;
`);
await db.exec(`ALTER TABLE item_variants ADD CONSTRAINT test_variant_style_fk FOREIGN KEY(style_id) REFERENCES item_styles(id);
ALTER TABLE item_variants ADD CONSTRAINT test_variant_unique UNIQUE(style_id,colour);
ALTER TABLE item_compositions ADD CONSTRAINT test_composition_style_fk FOREIGN KEY(style_id) REFERENCES item_styles(id);
ALTER TABLE item_compositions ADD CONSTRAINT test_composition_unique UNIQUE(style_id,component_name_normalized);
ALTER TABLE item_detail_lines ADD CONSTRAINT test_detail_variant_fk FOREIGN KEY(variant_id) REFERENCES item_variants(id);`);
await db.exec(fs.readFileSync('master-merge-update/01-MASTER-MERGE.sql','utf8'));
console.log('Installation PASS');
const a='00000000-0000-0000-0000-000000000010',b='00000000-0000-0000-0000-000000000011';
await db.query(`INSERT INTO accounts(id,name,parent_group,gstin,op_bal_dr,op_bal_cr) VALUES($1,'Old A','Supplier','GST',100,0),($2,'Old B','Supplier','GST',20,0)`,[a,b]);
await db.exec(`INSERT INTO sales_orders(party_name,total_qty,total_amount) VALUES('Old A',10,1000),('Old B',20,2000);INSERT INTO printer_fabric_issues(printer_account,qty_issued,qty_received,qty_pending) VALUES('Old B',500,100,400);`);
const preview=()=>db.query('select erp_master_merge_plan($1,$2,$3,$4,$5,$6) p',['account',a,b,'New Account',120,0]);
let p=(await preview()).rows[0].p;console.log('Conflicts:',p.conflicts);assert.deepEqual(p.conflicts,[]);assert.equal(p.impact.sales_orders,2);assert.equal(p.impact.printer_fabric_issues,1);
await db.exec("UPDATE accounts SET mob='111'");
await db.query("UPDATE accounts SET mob='222' WHERE id=$1",[b]);
assert.ok((await preview()).rows[0].p.conflicts.some(c=>c.includes('mob')));
await db.exec('UPDATE accounts SET mob=NULL');
p=(await preview()).rows[0].p;
const request='00000000-0000-0000-0000-000000000090';
const merge=(token=p.token,reviewed=true)=>db.query('select erp_merge_masters($1,$2,$3,$4,$5,$6,$7,$8,$9) r',['account',a,b,'New Account',120,0,token,request,reviewed]);
await assert.rejects(()=>merge(p.token,false),/Review/);
await db.exec("UPDATE sales_orders SET total_amount=1001 WHERE party_name='Old A'");await assert.rejects(()=>merge(),/changed after/);p=(await preview()).rows[0].p;
let result=(await merge()).rows[0].r;assert.equal(result.target_name,'New Account');assert.equal((await db.query('select count(*) n from accounts')).rows[0].n,1);
assert.equal((await db.query('select op_bal_dr from accounts')).rows[0].op_bal_dr,'120');assert.equal((await db.query("select count(*) n from sales_orders where party_name='New Account'")).rows[0].n,2);
assert.deepEqual((await db.query('select qty_issued,qty_received,qty_pending from printer_fabric_issues')).rows[0],{qty_issued:'500',qty_received:'100',qty_pending:'400'});
assert.deepEqual((await merge()).rows[0].r,result);
await assert.rejects(()=>db.query("INSERT INTO accounts(id,name) VALUES($1,'Old B')",[b]),/merged/);
await assert.rejects(()=>db.exec("INSERT INTO sales_orders(party_name) VALUES('Old A')"),/merged/);
await db.exec('UPDATE erp_user_access SET is_owner=false');await assert.rejects(()=>preview(),/Only an active Owner/);await db.exec('UPDATE erp_user_access SET is_owner=true');

const oa='00000000-0000-0000-0000-000000000021',ob='00000000-0000-0000-0000-000000000022';
await db.query("INSERT INTO stitch_operators(id,operator_name) VALUES($1,'Op A'),($2,'Op B')",[oa,ob]);
await db.query("INSERT INTO stitch_issue_vouchers(operator_id,operator_name,total_pieces) VALUES($1,'Op B',49)",[ob]);
const opPlan=async()=> (await db.query("select erp_master_merge_plan('operator',$1,$2,'Combined Op',NULL,NULL) p",[oa,ob])).rows[0].p;
let op=await opPlan();assert.deepEqual(op.conflicts,[]);
await db.exec("INSERT INTO test_locks SELECT 'stitch_issue_vouchers',id::text FROM stitch_issue_vouchers");assert.ok((await opPlan()).conflicts.some(c=>c.includes('Protected')));await db.exec('DELETE FROM test_locks');
// A badly behaved existing trigger must roll the entire merge back.
await db.exec("CREATE FUNCTION break_quantity() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN NEW.total_pieces=NEW.total_pieces+1;RETURN NEW;END$$; CREATE TRIGGER break_quantity BEFORE UPDATE ON stitch_issue_vouchers FOR EACH ROW EXECUTE FUNCTION break_quantity()");
await assert.rejects(()=>db.query("select erp_merge_masters('operator',$1,$2,'Combined Op',NULL,NULL,$3,gen_random_uuid(),true)",[oa,ob,op.token]),/additional data/);
assert.equal((await db.query('SELECT count(*) n FROM stitch_operators')).rows[0].n,2);assert.equal((await db.query('SELECT total_pieces FROM stitch_issue_vouchers')).rows[0].total_pieces,49);
await db.exec('DROP TRIGGER break_quantity ON stitch_issue_vouchers');op=await opPlan();
await db.query("select erp_merge_masters('operator',$1,$2,'Combined Op',NULL,NULL,$3,gen_random_uuid(),true)",[oa,ob,op.token]);
assert.equal((await db.query('SELECT operator_id FROM stitch_issue_vouchers')).rows[0].operator_id,oa);
const ia='00000000-0000-0000-0000-000000000031',ib='00000000-0000-0000-0000-000000000032',ca='00000000-0000-0000-0000-000000000041',cb='00000000-0000-0000-0000-000000000042';
await db.query("INSERT INTO item_styles(id,item_name) VALUES($1,'Item A'),($2,'Item B')",[ia,ib]);
await db.query("INSERT INTO item_compositions(id,style_id,component_name,component_name_normalized,qty_per_set) VALUES($1,$2,'Kurta','kurta',1),($3,$4,'Kurta','kurta',1)",[ca,ia,cb,ib]);
await db.query("INSERT INTO item_variants(style_id,colour,measurement_sheet_url) VALUES($1,'Red','https://example.com/a.xlsx'),($2,'Blue','https://example.com/b.xlsx')",[ia,ib]);
await db.exec('CREATE TABLE component_refs(job_id uuid,component_id uuid,status text,PRIMARY KEY(job_id,component_id))');
await db.query("INSERT INTO component_refs VALUES(gen_random_uuid(),$1,'approved')",[cb]);
let ip=(await db.query("select erp_master_merge_plan('item',$1,$2,'Combined Item',NULL,NULL) p",[ia,ib])).rows[0].p;assert.deepEqual(ip.conflicts,[]);
await db.query("select erp_merge_masters('item',$1,$2,'Combined Item',NULL,NULL,$3,gen_random_uuid(),true)",[ia,ib,ip.token]);
assert.equal((await db.query('select count(*) n from item_compositions')).rows[0].n,1);assert.equal((await db.query('select component_id from component_refs')).rows[0].component_id,ca);
assert.equal((await db.query("select count(*) n from item_variants where measurement_sheet_url is not null and style_id=$1",[ia])).rows[0].n,2);

// Field selections are enforced by the server, not just the UI.
const fa='00000000-0000-0000-0000-000000000051',fb='00000000-0000-0000-0000-000000000052';
await db.query("INSERT INTO accounts(id,name,mob,add1) VALUES($1,'Choice A','111','Address A'),($2,'Choice B','222','Address B')",[fa,fb]);
const fp=async choices=>(await db.query("select erp_master_merge_plan('account',$1,$2,'Selected Account',0,0,$3::jsonb) p",[fa,fb,JSON.stringify(choices)])).rows[0].p;
let cp=await fp({});assert.equal(cp.differences.length,2);assert.equal(cp.conflicts.length,2);
const pick={'field:mob':'b','field:add1':'a'};cp=await fp(pick);assert.deepEqual(cp.conflicts,[]);assert.equal(cp.target.mob,'222');assert.equal(cp.target.add1,'Address A');
assert.ok((await fp({'field:mob':'other'})).conflicts.length);
await assert.rejects(()=>db.query("select erp_merge_masters('account',$1,$2,'Selected Account',0,0,$3,gen_random_uuid(),true,$4::jsonb)",[fa,fb,cp.token,JSON.stringify({...pick,'field:mob':'a'})]),/changed after/);
await db.query("select erp_merge_masters('account',$1,$2,'Selected Account',0,0,$3,gen_random_uuid(),true,$4::jsonb)",[fa,fb,cp.token,JSON.stringify(pick)]);
assert.equal((await db.query('select mob from accounts where id=$1',[fa])).rows[0].mob,'222');
// Whole variant/measurement/material and composition decisions keep stable IDs.
const sa='00000000-0000-0000-0000-000000000061',sb='00000000-0000-0000-0000-000000000062',va='00000000-0000-0000-0000-000000000071',vb='00000000-0000-0000-0000-000000000072';
await db.query("INSERT INTO item_styles(id,item_name) VALUES($1,'Colour A'),($2,'Colour B')",[sa,sb]);
await db.query("INSERT INTO item_compositions(style_id,component_name,component_name_normalized,qty_per_set) VALUES($1,'Pant','pant',1),($2,'Pant','pant',2)",[sa,sb]);
await db.query("INSERT INTO item_variants(id,style_id,colour,measurement_sheet_url) VALUES($1,$2,'Red','https://example.com/source-a.xlsx'),($3,$4,'Red','https://example.com/source-b.xlsx')",[va,sa,vb,sb]);
await db.query("INSERT INTO item_detail_lines(variant_id,material_name,quantity) VALUES($1,'Cotton A',1),($2,'Cotton B',2)",[va,vb]);
let ip2=(await db.query("select erp_master_merge_plan('item',$1,$2,'Chosen Colour',NULL,NULL) p",[sa,sb])).rows[0].p;assert.equal(ip2.differences.length,2);assert.equal(ip2.conflicts.length,2);
const vp={'composition':'b',['variant:'+va]:'b'};
ip2=(await db.query("select erp_master_merge_plan('item',$1,$2,'Chosen Colour',NULL,NULL,$3::jsonb) p",[sa,sb,JSON.stringify(vp)])).rows[0].p;assert.deepEqual(ip2.conflicts,[]);
await db.query("select erp_merge_masters('item',$1,$2,'Chosen Colour',NULL,NULL,$3,gen_random_uuid(),true,$4::jsonb)",[sa,sb,ip2.token,JSON.stringify(vp)]);
assert.equal((await db.query('select measurement_sheet_url from item_variants where id=$1',[va])).rows[0].measurement_sheet_url,'https://example.com/source-b.xlsx');
assert.equal((await db.query('select qty_per_set from item_compositions where style_id=$1',[sa])).rows[0].qty_per_set,2);
const materials=(await db.query('select material_name,quantity from item_detail_lines where variant_id=$1',[va])).rows;assert.equal(materials.length,1);assert.equal(materials[0].material_name,'Cotton B');
assert.ok(JSON.stringify((await db.query("select changes from erp_master_merge_log where target_id=$1",[sa])).rows).includes('Cotton A'));
console.log('PASS explicit per-block choices, missing/invalid choice rejection, tamper rejection, mixed sources, chosen composition, variant sheet/material selection and archived discarded details');
console.log('PASS operator links, locked voucher protection, trigger side-effect rollback, item attachments, component reconciliation and composite primary keys');
console.log('PASS account preview, stale version, atomic merge, quantities, opening balance, retry, retired IDs/names, owner permissions');
}finally{await db.close();}})().catch(e=>{console.error(e);process.exit(1)});
