const path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');const fs=require('fs');const assert=require('node:assert/strict');const crypto=require('node:crypto');
(async()=>{
 const db=new PGlite();
 await db.exec(`CREATE ROLE authenticated; CREATE ROLE anon; CREATE SCHEMA auth;
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 GRANT USAGE ON SCHEMA auth TO authenticated; GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated;
 CREATE TABLE item_styles(id uuid primary key default gen_random_uuid(),job_card_no text,design_code text,style_no text,set_type text,import_key text,primary_image_url text,linked_job_card_id uuid,updated_at timestamptz);
 CREATE TABLE item_variants(id uuid primary key default gen_random_uuid(),style_id uuid references item_styles(id) ON DELETE CASCADE,job_card_no text,colour text,colour_normalized text,style_no text,set_type text,variant_status text,match_level text,import_key text,import_source text,source_row_start int,source_row_end int,updated_at timestamptz);
 CREATE TABLE item_detail_lines(id uuid primary key default gen_random_uuid(),variant_id uuid references item_variants(id) ON DELETE CASCADE,category text,material_name text,material_name_normalized text,quantity numeric,unit text,secondary_quantity numeric,secondary_unit text,notes text,source_text text,source_row int,review_status text,review_note text,import_key text);
 CREATE TABLE item_compositions(id uuid primary key default gen_random_uuid(),style_id uuid references item_styles(id) ON DELETE CASCADE,component_name text,component_name_normalized text,qty_per_set int CHECK(qty_per_set>0),unit text,sort_order int,notes text,updated_at timestamptz);
 CREATE TABLE job_cards(id uuid primary key default gen_random_uuid(),job_card_no text);
 CREATE TABLE sales_order_items(id uuid primary key default gen_random_uuid(),item_name text);
 CREATE TABLE production_batches(id uuid primary key default gen_random_uuid(),job_card_no text,style_name text);
 CREATE TABLE stitching_entries(id uuid primary key default gen_random_uuid(),job_card_ref text,style_name text);
 CREATE TABLE qc_entries(id uuid primary key default gen_random_uuid(),job_card_ref text,style_name text);
 GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO authenticated;`);
 for(const t of ['item_styles','item_variants','item_detail_lines','item_compositions','job_cards'])await db.exec(`ALTER TABLE ${t} ENABLE ROW LEVEL SECURITY;CREATE POLICY fixture ON ${t} TO authenticated USING(true) WITH CHECK(true);`);
 await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations/20260908180000_original_item_create.sql'),'utf8'));
 await db.exec(`SET ROLE authenticated;SET request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';`);
 const make=(name='STYLE-A')=>({style:{job_card_no:name,design_code:name,style_no:name,set_type:'3PC',import_key:crypto.randomUUID(),_compositions:[{component_name:'Kurta',qty_per_set:1,unit:'Pcs',sort_order:0}]},variants:[{colour:'Red',style_no:name,set_type:'3PC',import_key:crypto.randomUUID(),_details:[{category:'fabric_material',material_name:'Cotton',material_name_normalized:'Cotton',quantity:'2',unit:'Mtr',secondary_quantity:null,secondary_unit:'',notes:'',source_text:'Cotton',source_row:0,import_key:crypto.randomUUID()}]}]});
 const create=async(r,p)=>(await db.query('SELECT create_original_item($1::uuid,$2::jsonb,$3::jsonb) AS result',[r,JSON.stringify(p.style),JSON.stringify(p.variants)])).rows[0].result;
 const counts=async()=>JSON.stringify((await db.query('SELECT (SELECT count(*) FROM item_styles) s,(SELECT count(*) FROM item_variants) v,(SELECT count(*) FROM item_detail_lines) d,(SELECT count(*) FROM item_compositions) c,(SELECT count(*) FROM item_manual_save_requests) r')).rows);
 const payload=make(),rid=crypto.randomUUID(),first=await create(rid,payload);let before=await counts();
 assert.deepEqual(await create(rid,payload),first);assert.equal(await counts(),before);console.log('PASS original create replay preserves IDs and counts');
 const variant=(await db.query('SELECT * FROM item_variants WHERE id=$1',[first.variant_ids[0]])).rows[0];assert.equal(variant.colour,'RED');assert.equal(variant.colour_normalized,'red');assert.equal(variant.import_source,'manual');console.log('PASS original colour normalization and manual provenance');
 const changed=structuredClone(payload);changed.style.set_type='2PC';await assert.rejects(()=>create(rid,changed),/another payload/);console.log('PASS request identity cannot be reused with changed data');
 const bad=make();bad.style._compositions[0].qty_per_set=0;await assert.rejects(()=>create(crypto.randomUUID(),bad),/positive whole/);assert.equal(await counts(),before);console.log('PASS composition failure rolls back style, variant, details and receipt');
 const lineId=(await db.query('SELECT id FROM item_detail_lines WHERE variant_id=$1',[first.variant_ids[0]])).rows[0].id;
 const edit=(lines)=>db.query('SELECT edit_original_item_variant($1::uuid,$2::jsonb,$3::jsonb)',[first.variant_ids[0],JSON.stringify({colour:'Blue',style_no:'STYLE-A',set_type:'3PC'}),JSON.stringify(lines)]);
 await edit([{id:lineId,material_name_normalized:'Cotton',quantity:3,unit:'Mtr',secondary_quantity:null,secondary_unit:'',notes:''}]);
 assert.equal((await db.query('SELECT colour_normalized FROM item_variants WHERE id=$1',[first.variant_ids[0]])).rows[0].colour_normalized,'blue');
 assert.equal(Number((await db.query('SELECT quantity FROM item_detail_lines WHERE id=$1',[lineId])).rows[0].quantity),3);
 console.log('PASS original header/detail edit updates together');
 await assert.rejects(()=>edit([{id:crypto.randomUUID(),quantity:9}]),/does not belong/);
 assert.equal(Number((await db.query('SELECT quantity FROM item_detail_lines WHERE id=$1',[lineId])).rows[0].quantity),3);
 console.log('PASS wrong-parent detail edit rejected without partial change');
 const deleteVariant=id=>db.query('SELECT delete_original_item_variant($1::uuid)',[id]);
 await db.query("INSERT INTO job_cards(job_card_no) VALUES($1)",[payload.style.job_card_no]);
 await db.exec('RESET ROLE;ALTER POLICY fixture ON job_cards TO authenticated USING(false) WITH CHECK(true);SET ROLE authenticated;');
 await assert.rejects(()=>deleteVariant(first.variant_ids[0]),/referenced/);assert.equal(await counts(),before);console.log('PASS RLS-hidden business reference blocks deletion');
 await db.exec('RESET ROLE;DELETE FROM job_cards;ALTER POLICY fixture ON job_cards TO authenticated USING(true) WITH CHECK(true);SET ROLE authenticated;');
 await db.exec('RESET ROLE;ALTER POLICY fixture ON item_detail_lines TO authenticated USING(false) WITH CHECK(true);SET ROLE authenticated;');
 await assert.rejects(()=>deleteVariant(first.variant_ids[0]),/material lines/);console.log('PASS hidden child cannot be cascade-deleted');
 await db.exec('RESET ROLE;ALTER POLICY fixture ON item_detail_lines TO authenticated USING(true) WITH CHECK(true);SET ROLE authenticated;');
 before=await counts();
 await db.exec('RESET ROLE;DROP POLICY fixture ON item_styles;CREATE POLICY fixture_read ON item_styles FOR SELECT TO authenticated USING(true);CREATE POLICY fixture_insert ON item_styles FOR INSERT TO authenticated WITH CHECK(true);CREATE POLICY fixture_update ON item_styles FOR UPDATE TO authenticated USING(true) WITH CHECK(true);SET ROLE authenticated;');
 await assert.rejects(()=>deleteVariant(first.variant_ids[0]),/Parent deletion/);assert.equal(await counts(),before);console.log('PASS denied parent delete rolls back already deleted children');
 await db.exec('RESET ROLE;DROP POLICY fixture_read ON item_styles;DROP POLICY fixture_insert ON item_styles;DROP POLICY fixture_update ON item_styles;CREATE POLICY fixture ON item_styles TO authenticated USING(true) WITH CHECK(true);SET ROLE authenticated;');
 await deleteVariant(first.variant_ids[0]);assert.equal((await db.query('SELECT count(*)::int n FROM item_styles')).rows[0].n,0);assert.equal((await db.query('SELECT count(*)::int n FROM item_compositions')).rows[0].n,0);console.log('PASS original last-variant rule deletes parent and compositions');
 const a=await create(crypto.randomUUID(),make('SAME')),b=await create(crypto.randomUUID(),make('SAME'));
 const merge=g=>db.query('SELECT merge_original_item_styles($1::jsonb)',[JSON.stringify(g)]);
 await merge([{keeperId:a.style_id,duplicateIds:[b.style_id]}]);
 assert.equal((await db.query('SELECT style_id FROM item_variants WHERE id=$1',[b.variant_ids[0]])).rows[0].style_id,a.style_id);
 assert.equal((await db.query('SELECT count(*)::int n FROM item_compositions WHERE style_id=$1',[a.style_id])).rows[0].n,2);console.log('PASS merge preserves variant IDs and moves compositions to original keeper');
 await deleteVariant(a.variant_ids[0]);assert.equal((await db.query('SELECT count(*)::int n FROM item_styles WHERE id=$1',[a.style_id])).rows[0].n,1);console.log('PASS deleting one of several variants preserves parent');
 const other=await create(crypto.randomUUID(),make('OTHER'));before=await counts();await assert.rejects(()=>merge([{keeperId:a.style_id,duplicateIds:[other.style_id]}]),/same original style/);assert.equal(await counts(),before);console.log('PASS merge rejects unrelated styles');
 const hidden=await create(crypto.randomUUID(),make('SAME'));
 await db.exec('RESET ROLE;ALTER POLICY fixture ON item_variants TO authenticated USING(false) WITH CHECK(true);SET ROLE authenticated;');
 await assert.rejects(()=>merge([{keeperId:a.style_id,duplicateIds:[hidden.style_id]}]),/child records/);console.log('PASS RLS-hidden children block unsafe merge');
 await db.exec('RESET ROLE;ALTER POLICY fixture ON item_variants TO authenticated USING(true) WITH CHECK(true);SET ROLE authenticated;');
 await db.exec("SET request.jwt.claim.sub='';");await assert.rejects(()=>create(crypto.randomUUID(),make()),/Sign in/);console.log('PASS signed-out mutation rejected');
 await db.close();
 const ts=require('typescript'),vm=require('vm');const parse=path=>{const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports,console});return JSON.stringify(exports.parseRangraahiWIP())};
 assert.equal(crypto.createHash('sha256').update(parse(path.join(__dirname,'../src/lib/services/itemImportParser.ts'))).digest('hex'), '30ffc6a51ed5c542e23f6a0ad57bb006c37a5378fb67fb31ace94745121ef7ca');console.log('PASS original WIP parser output unchanged byte-for-byte');
})().catch(e=>{console.error(e);process.exitCode=1});
