const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');const {createRequire}=require('node:module');const ts=require('typescript');const root=path.resolve(__dirname,'..');const requireApp=createRequire(path.join(root,'package.json'));
function load(rel,mocks={}){const exports={};const code=ts.transpileModule(fs.readFileSync(path.join(root,rel),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(code,{exports,require:id=>id in mocks?mocks[id]:requireApp(id),console,crypto:require('node:crypto').webcrypto,setTimeout,clearTimeout,URL});return exports;}
(async()=>{
const calc=load('src/lib/services/orderCalculations.ts');assert.equal(calc.salesTotals([{qty:100,price:123.45}],5).totalAmount,12962.25);assert.equal(calc.sizeBreakupError('S/40,M/60',100),null);for(const t of ['S/40,M/59','S/40,s/60','','S/-1,M/101'])assert.ok(calc.sizeBreakupError(t,100));console.log('PASS client GST and size conservation including duplicates');
const React=requireApp('react');const {renderToStaticMarkup}=requireApp('react-dom/server');
const modal=load('src/app/sales-orders/components/NewSalesOrderModal.tsx',{'@/lib/services/orderCalculations':calc,'@/lib/hooks/useRealtimeTable':{useRealtimeTable(){}},'@/lib/services/salesOrderService':{},'@/lib/services/accountService':{},'next/navigation':{useRouter:()=>({})},'@/lib/supabase/client':{},'@/contexts/AuthContext':{useAuth:()=>({username:'local'})}});
const html=renderToStaticMarkup(React.createElement(modal.default,{lang:'en',onClose(){},onSaved(){},editOrder:{date:'08-09-2026',vchNo:'LOCAL',partyName:'LOCAL',partyType:'external',items:[{itemName:'LOCAL',paramSize:'S/40,M/60',qty:100,unit:'Pcs.',price:123.45}],gstPercent:5}}));assert.ok(html.includes('GST (%)'));assert.ok(html.includes('12962.25'));assert.ok(html.includes('Size total:'));console.log('PASS actual edit form renders saved GST and size allocation');
// Exercise existing Handwork-capable voucher service with isolated table fixtures.
const tables={emb_issue_vouchers:[],emb_receive_vouchers:[],cutting_stock:[],cutting_movement_history:[]};
function from(table){let filters=[],op='select',payload,single=false;const q={select(){return q},order(){return q},eq(k,v){filters.push(r=>r[k]===v);return q},insert(p){op='insert';payload=p;return q},update(p){op='update';payload=p;return q},single(){single=true;return q},then(resolve,reject){try{let rows=tables[table].filter(r=>filters.every(f=>f(r)));if(op==='insert'){const row={id:require('crypto').randomUUID(),...payload};tables[table].push(row);rows=[row];}if(op==='update')rows.forEach(r=>Object.assign(r,payload));return Promise.resolve({data:single?rows[0]:rows,error:null}).then(resolve,reject);}catch(e){return Promise.reject(e).then(resolve,reject);}}};return q;}
const {embroideryVoucherService:svc}=load('src/lib/services/embroideryVoucherService.ts',{'@/lib/supabase/client':{createClient:()=>({from})},'@/lib/services/fabricInventoryService':{fabricInventoryService:{}}});
assert.equal(await svc.getNextIssueVoucherNo(true),'HWI-0001');assert.equal(await svc.getNextReceiveVoucherNo(true),'HWR-0001');
const issue=await svc.createIssueVoucher({voucherNo:'HWI-0001',voucherDate:'2026-09-08',jobCardRef:'JC-LOCAL',jobCardId:'',processType:'handwork',issueSource:'fresh_cutting',issueType:'part_component',operatorName:'LOCAL OPERATOR',cuttingItems:[{component:'Kurta',pieces:12,unit:'Pcs'}],fabricItems:[],accessoryItems:[],status:'open'});assert.equal(tables.emb_issue_vouchers[0].process_type,'handwork');
const received={voucherNo:'HWR-0001',voucherDate:'2026-09-08',issueVoucherId:issue.id,issueVoucherNo:issue.voucherNo,jobCardRef:issue.jobCardRef,cuttingItems:[{component:'Kurta',receivedPieces:10,unit:'Pcs'}],fabricItems:[],accessoryItems:[]};await svc.createReceiveVoucher(received);assert.equal(tables.emb_issue_vouchers[0].status,'partially_received');assert.equal((await svc.buildReceiveCuttingItems(issue))[0].balancePieces,2);assert.equal(tables.cutting_stock[0].available_pieces,10);assert.equal(tables.cutting_stock[0].job_card_ref,'JC-LOCAL');console.log('PASS Handwork issue12/receive10 retains2 pending and posts10 linked component pieces');
await svc.createReceiveVoucher({...received,voucherNo:'HWR-0002',cuttingItems:[{component:'Kurta',receivedPieces:2,unit:'Pcs'}]});assert.equal(tables.emb_issue_vouchers[0].status,'fully_received');assert.equal((await svc.buildReceiveCuttingItems(issue))[0].balancePieces,0);assert.equal(await svc.getNextIssueVoucherNo(false),'EIV-0001');console.log('PASS final Handwork receipt closes balance, numbering stays separate from embroidery');
})().catch(e=>{console.error(e);process.exitCode=1});
