const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');const {createRequire}=require('node:module');const ts=require('typescript');const root=path.resolve(__dirname,'..');const requireApp=createRequire(path.join(root,'package.json'));
function load(rel,mocks={}){const exports={};const source=fs.readFileSync(path.join(root,rel),'utf8');const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(code,{exports,require:(id)=>id in mocks?mocks[id]:requireApp(id),console,crypto:require('node:crypto').webcrypto,setTimeout,clearTimeout,URL});return exports;}
(async()=>{
 const React=requireApp('react');const {renderToStaticMarkup}=requireApp('react-dom/server');
 const workflows=load('src/app/masters/items/components/OriginalItemWorkflows.tsx',{'@/lib/supabase/client':{supabase:{}},'@/lib/supabase/services/originalItemSave':{saveOriginalItem(){throw Error('No writes in render test');},recoverPendingItemSave(){},PendingItemSaveError:class extends Error{}},'next/link':{__esModule:true,default:({children,href})=>React.createElement('a',{href},children)},sonner:{toast:{}}});
 const html=renderToStaticMarkup(React.createElement(workflows.NewItemModal,{onClose(){},onCreated(){}}));
 for(const text of ['New Item','Drop image here','MEASUREMENT SHEET','Drop sheet here','Colour','Production Sub-Units','Add Fabric / Material','Add Manufacturing Work','Add Accessories / Raw Materials'])assert.ok(html.toLowerCase().includes(text.toLowerCase()),text);
 assert.ok(!html.includes('Import Key'));console.log('PASS actual restored NewItemModal renders original uploads, colour, composition and specification controls without an Import Key field');
 const itemRoute=fs.readFileSync(path.join(root,'src/app/item-master/page.tsx'),'utf8');const itemClient=fs.readFileSync(path.join(root,'src/app/masters/items/components/ItemMasterClient.tsx'),'utf8');assert.ok(itemRoute.includes('ItemMasterClient'));assert.ok(itemClient.includes('<NewItemModal'));assert.ok(!itemClient.includes('ItemFormModal'));console.log('PASS original and current Item Master route wiring selects restored modal');
 const {validateQCQuantities}=load('src/lib/quantityValidation.ts');assert.equal(validateQCQuantities([{piecesReceived:100,passCount:90,failCount:10}]),null);assert.ok(validateQCQuantities([{piecesReceived:100,passCount:95,failCount:10}]));assert.ok(validateQCQuantities([{piecesReceived:100,passCount:1.5,failCount:0}]));assert.ok(validateQCQuantities([{piecesReceived:100,passCount:-1,failCount:0}]));console.log('PASS QC whole-number and conservation validation');
 let captured;const result={id:'local-id',job_card_no:'JC',party_name:'PARTY',stage:'qc'};const query={update(row){captured=row;return this},eq(){return this},select(){return this},single:async()=>({data:result,error:null})};const {jobCardService}=load('src/lib/services/jobCardService.ts',{'@/lib/supabase/client':{createClient:()=>({from:()=>query})}});await jobCardService.update('local-id',{stage:'qc'},'tester');assert.deepEqual(Object.keys(captured).sort(),['stage','updated_by']);console.log('PASS partial job-card stage update does not reset other fields');
 const {formatAuditTimestamp}=load('src/lib/auditTrail.ts');assert.equal(formatAuditTimestamp('invalid'),'—');console.log('PASS invalid audit date is displayed safely');
 const client=fs.readFileSync(path.join(root,'src/lib/supabase/client.ts'),'utf8');const middleware=fs.readFileSync(path.join(root,'src/middleware.ts'),'utf8');assert.ok(client.includes('export const supabase'));assert.ok(!client.includes('window.fetch'));assert.ok(!middleware.includes('erp_local_auth'));assert.ok(middleware.includes('auth.getUser()'));console.log('PASS shared browser client and server validation do not use the old local-login bypass');
})().catch(e=>{console.error(e);process.exitCode=1;});
