const {PGlite}=require('@electric-sql/pglite');const fs=require('fs');const assert=require('assert');
(async()=>{const db=new PGlite();const q=(s,p)=>db.query(s,p);const owner='10000000-0000-0000-0000-000000000001';const uid=n=>'20000000-0000-0000-0000-'+String(n).padStart(12,'0');
async function as(id,sql,p){await db.exec('BEGIN');try{await q("select set_config('request.jwt.claim.sub',$1,true)",[id]);await db.exec('SET LOCAL ROLE authenticated');let r=await q(sql,p);await db.exec('COMMIT');return r;}catch(e){await db.exec('ROLLBACK');throw e;}}
try{
await db.exec(fs.readFileSync(require('path').join(__dirname,'team-schema-fixture.sql'),'utf8'));await db.exec(fs.readFileSync(require('path').join(__dirname,'../TEAM-ACCESS-UPDATE.sql'),'utf8'));
const tables=['stitch_issue_vouchers','stitch_issue_components','stitch_receive_vouchers','stitch_receive_components','cutting_entries','fabric_inventory','contractor_issue_vouchers'];for(const t of tables)await db.exec(`CREATE TRIGGER erp_activity_capture AFTER INSERT OR UPDATE OR DELETE ON ${t} FOR EACH ROW EXECUTE FUNCTION erp_record_activity()`);
await q('insert into auth.users(id,email) values($1,$2)',[owner,'existing@example.test']);await q("insert into erp_user_access(user_id,display_name,active,is_owner,is_admin,permissions) values($1,'Existing owner',true,true,true,'{}')",[owner]);
const profiles=JSON.parse(fs.readFileSync(require('path').join(__dirname,'team-permissions.json'),'utf8')).profiles;
for(let i=0;i<profiles.length;i++){const p=profiles[i];await q('insert into auth.users(id,email) values($1,$2)',[uid(i),p.username+'@staff.rangraahi.invalid']);await as(owner,'select erp_apply_team_profile($1,$2)',[uid(i),p.username]);for(const module of ['items','accounts','operators','sales','jobs','grey','dyeing','receive','fabric','cutting','embroidery','handwork','stitching','qc','contractor','assembly','conversion','finishing','ready','dispatch','ledger','audit','users'])for(const action of ['view','create','edit','delete']){const r=await as(uid(i),'select erp_can($1,$2) allowed',[module,action]);assert.equal(r.rows[0].allowed,p.owner||!!p.permissions[module]?.includes(action),p.username+' '+module+' '+action);}}
console.log('PASS all 10 profiles and 920 permission decisions; multiple owners');
const babu=uid(5);let r=await as(babu,'select erp_save_team_voucher($1,$2,$3,$4) data',['stitch_issue',null,{voucher_no:'SI-1',voucher_date:'2026-09-15',total_pieces:10},[{component:'Kurta',issued_qty:10,received_qty:0,pending_qty:10}]]);let issue=r.rows[0].data.id;let comp=(await q('select id from stitch_issue_components where issue_voucher_id=$1',[issue])).rows[0].id;
await assert.rejects(()=>as(babu,'select erp_save_team_voucher($1,$2,$3,$4)',['stitch_issue',issue,{remarks:'bad'},[{component:'Kurta',issued_qty:20}]]),/permission/);
r=await as(babu,'select erp_save_team_voucher($1,$2,$3,$4) data',['stitch_receive',null,{voucher_no:'SR-1',voucher_date:'2026-09-15',issue_voucher_id:issue},[{issue_component_id:comp,component:'Kurta',received_qty:6}]]);
assert.equal((await q('select received_qty from stitch_issue_components where id=$1',[comp])).rows[0].received_qty,6);
await assert.rejects(()=>as(babu,'select erp_save_team_voucher($1,$2,$3,$4)',['stitch_receive',null,{voucher_no:'BAD',issue_voucher_id:issue},[{issue_component_id:comp,component:'Kurta',received_qty:5}]]),/exceeds/);
assert.equal((await q("select count(*)::int n from stitch_receive_vouchers where voucher_no='BAD'")).rows[0].n,0);
await assert.rejects(()=>as(owner,"update stitch_issue_vouchers set remarks='changed' where id=$1",[issue]),/later entry/);
await assert.rejects(()=>as(owner,'delete from stitch_issue_vouchers where id=$1',[issue]),/later entry/);
console.log('PASS create-only receipt updates source totals atomically; over-receipt rolls back; settled owner edits/deletes blocked');
let id=(await q("insert into contractor_issue_vouchers(voucher_no) values('CI-free') returning id")).rows[0].id;
await as(owner,"update contractor_issue_vouchers set remarks='one' where id=$1",[id]);await as(owner,"update contractor_issue_vouchers set remarks='two' where id=$1",[id]);r=await as(owner,"select erp_module_history('contractor') data");const ev=r.rows[0].data.filter(x=>x.record_id===id&&x.action==='UPDATE');assert.equal(ev.length,2);assert.equal(ev[0].performed_by,'Existing owner');assert.equal(ev[0].changes.remarks.before,'one');assert.equal(ev[0].changes.remarks.after,'two');
console.log('PASS every edit retains actor, timestamp, before/after values');
let fabric=(await q("insert into fabric_inventory(fabric_name,stock_qty) values('Test',100) returning id")).rows[0].id;
r=await as(uid(8),'select erp_save_team_voucher($1,$2,$3,$4) data',['cutting',null,{entry_no:'CUT-1',roll_details:[{fabricRollId:fabric,fabricConsumedQty:20}],emb_receive_items:[]},[{component:'Kurta',total_pieces:10,net_pieces:10,rejections:0}]]);assert.equal(Number((await q('select stock_qty from fabric_inventory where id=$1',[fabric])).rows[0].stock_qty),80);
await assert.rejects(()=>as(uid(8),'select erp_save_team_voucher($1,$2,$3,$4)',['cutting',null,{entry_no:'CUT-bad',roll_details:[{fabricRollId:fabric,fabricConsumedQty:90}],emb_receive_items:[]},[{component:'Kurta',total_pieces:10}]]),/insufficient/);assert.equal(Number((await q('select stock_qty from fabric_inventory where id=$1',[fabric])).rows[0].stock_qty),80);
console.log('PASS cutting creator posts stock atomically; insufficient stock rolls back');
}catch(e){console.error(e.message,e.stack,e.query?.slice(-800));process.exitCode=1;}finally{await db.close();}})();
