'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
import {useAuth} from '@/contexts/AuthContext';
import VoucherDetails from '@/components/VoucherDetails';
import SearchableSelect from '@/components/SearchableSelect';
import {reportFieldIssue} from '@/lib/issueNavigation';
type Row={id:string;receive_voucher_id:string;voucher_no:string;job_card_ref:string;operator_name:string;component:string;size_breakdown:unknown;part_number?:string;pending_qty:number;quality_reason:string};
export default function StitchReworkPanel({onSaved}:{onSaved:()=>void}){
 const {can}=useAuth();const [rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[selected,setSelected]=useState<Row|null>(null),[qty,setQty]=useState(''),[quality,setQuality]=useState('normal'),[reason,setReason]=useState(''),[date,setDate]=useState(''),[busy,setBusy]=useState(false);
 const request=useRef(''),inFlight=useRef(false),alert=useRef<HTMLParagraphElement>(null);
 const load=useCallback(async()=>{try{const r=await createClient().rpc('erp_stitch_rework_pending');if(r.error)throw r.error;setRows(r.data||[]);setError('');}catch(e){setError((e as Error).message);}},[]);
 useEffect(()=>{void load();const refresh=()=>void load();window.addEventListener('erp-data-changed',refresh);return()=>window.removeEventListener('erp-data-changed',refresh)},[load]);
 function fail(message:string){setError(message);requestAnimationFrame(()=>reportFieldIssue(message,alert.current));}
 async function save(){if(inFlight.current||!selected)return;const n=Number(qty);if(!Number.isInteger(n)||n<=0||n>selected.pending_qty){fail('Enter whole pieces between 1 and the remaining rework quantity.');return;}if(quality==='final_reject'&&!reason.trim()){fail('Enter the final rejection reason.');return;}inFlight.current=true;setBusy(true);setError('');try{const r=await createClient().rpc('erp_complete_stitch_rework',{p_request:request.current,p_source:selected.id,p_quantity:n,p_quality:quality,p_reason:reason.trim(),p_date:date});if(r.error)throw r.error;setSelected(null);await load();onSaved();}catch(e){fail((e as Error).message);}finally{inFlight.current=false;setBusy(false)}}
 return <section className="border rounded-xl p-4 bg-amber-50/50 my-4"><h2 className="font-semibold">Repair / Rework Pending · {rows.reduce((n,r)=>n+Number(r.pending_qty),0)} pcs</h2><p className="text-xs text-muted-foreground mt-1">Held pieces are not available to contractors. Accepted repairs become payable once; Final Reject moves forward at stitching ₹0.</p>{error&&<p ref={alert} role="alert" tabIndex={-1} className="text-red-700 my-2">{error}</p>}<div className="space-y-2 mt-3">{rows.map(r=><div key={r.id} className="border-t pt-2 flex flex-wrap gap-3 items-center justify-between"><div className="text-sm"><VoucherDetails table="stitch_receive_vouchers" recordId={r.receive_voucher_id} label={r.voucher_no}/><p>{r.job_card_ref} · {r.operator_name} · {r.component} · {Array.isArray(r.size_breakdown)?r.size_breakdown.map((s:{size?:string})=>s.size).filter(Boolean).join(', '):''} · {r.pending_qty} pcs</p><p className="text-xs">{r.quality_reason}{r.part_number?' · Part: '+r.part_number:''}</p></div>{can('stitching','create')&&<button className="btn-secondary" onClick={()=>{request.current=crypto.randomUUID();setSelected(r);setQty(String(r.pending_qty));setQuality('normal');setReason('');setError('');setDate(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata'}).format(new Date()));}}>Record repair result</button>}</div>)}{!rows.length&&!error&&<p className="text-sm">No rework pending.</p>}</div>{selected&&<div className="fixed inset-0 z-[130] bg-black/40 p-3 flex items-center justify-center"><form onSubmit={e=>{e.preventDefault();void save()}} className="bg-white rounded-xl p-5 w-full max-w-lg max-h-[90dvh] overflow-auto space-y-3"><h3 className="font-semibold">Repair result · {selected.voucher_no} · {selected.component}</h3>{error&&<p role="alert" className="text-red-700">{error}</p>}<label className="block">Date<input required type="date" className="input-field" value={date} onChange={e=>setDate(e.target.value)} disabled={busy}/></label><label className="block">Result<SearchableSelect className="input-field" value={quality} onChange={e=>setQuality(e.target.value)} disabled={busy}><option value="normal">Accepted — stitching amount payable</option><option value="final_reject">Final Reject — forward stock, stitching ₹0</option></SearchableSelect></label><label className="block">Quantity · {selected.pending_qty} pending<input className="input-field" type="number" min="1" max={selected.pending_qty} step="1" required value={qty} onChange={e=>setQty(e.target.value)} disabled={busy}/></label><label className="block">Reason / Remarks<input className="input-field" required={quality==='final_reject'} value={reason} onChange={e=>setReason(e.target.value)} disabled={busy}/></label><div className="flex gap-3"><button type="button" className="btn-secondary" disabled={busy} onClick={()=>setSelected(null)}>Cancel</button><button className="btn-primary" disabled={busy}>{busy?'Saving…':'Save result'}</button></div></form></div>}</section>;
}
