'use client';
import {useEffect,useState,useRef} from 'react';
import Link from 'next/link';
import {useAuth} from '@/contexts/AuthContext';
import {createClient} from '@/lib/supabase/client';
export default function AssemblyOverview({refresh}:{refresh:string}){
 const loaded=useRef(false);
 const {can}=useAuth();const allowed=can('assembly')||can('conversion');const [rows,setRows]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;if(!allowed)return;if(!loaded.current)setBusy(true);(async()=>{try{const db=createClient();const {data,error}=await db.rpc('erp_pending_components',{p_job_ref:null});if(error)throw error;const groups=new Map<string,any>();for(const row of data||[]){const key=JSON.stringify([row.jobCardRef,row.size,row.colour]);const g=groups.get(key)||{key,job:row.jobCardRef,size:row.size,colour:row.colour,components:[]};g.components.push(row);groups.set(key,g);}const result=await Promise.all([...groups.values()].map(async g=>{const {data:composition,error}=await db.rpc('erp_assembly_composition',{p_job_ref:g.job});if(error||!composition?.length)return {...g,sets:null,missing:'Item composition unavailable'};const needed=composition.map((c:any)=>{const available=g.components.filter((p:any)=>p.component.trim().toLowerCase()===c.component.trim().toLowerCase()).reduce((n:number,p:any)=>n+Number(p.pendingQty||0),0);return {...c,available,sets:Number(c.qtyPerSet)>0?Math.floor(available/Number(c.qtyPerSet)):0};});return {...g,sets:Math.min(...needed.map((c:any)=>c.sets)),missing:needed.filter((c:any)=>c.sets===0).map((c:any)=>c.component).join(', ')};}));if(alive){loaded.current=true;setRows(result);setError('');}}catch(e){if(alive)setError(e instanceof Error?e.message:String(e));}finally{if(alive)setBusy(false);}})();return()=>{alive=false}},[allowed,refresh]);
 if(!allowed)return null;return <section className="card-surface p-4"><h2 className="font-semibold">Pending components / Assembly availability</h2>{busy?<p>Loading…</p>:error?<p role="alert">{error}</p>:rows.length===0?<p>No pending finished components.</p>:<div className="grid sm:grid-cols-2 gap-3 mt-3">{rows.map(g=><Link key={g.key} href="/contractor-finishing" className="border rounded-xl p-3"><strong>{g.job} · {g.colour} · {g.size}</strong><p>{g.components.map((c:any)=>`${c.component}: ${c.pendingQty}`).join(' · ')}</p>{can('assembly')&&<p>Possible sets: {g.sets??'—'} {g.missing&&`· Missing: ${g.missing}`}</p>}</Link>)}</div>}</section>;
}
