'use client';
import SearchableSelect from '@/components/SearchableSelect';

import {useEffect,useState,useRef,useCallback} from 'react';
import Link from 'next/link';
import StageRemarksButton from './StageRemarksButton';
import {componentApprovalStatus} from '@/lib/componentApprovalStatus';
import {createClient} from '@/lib/supabase/client';
import {useAuth} from '@/contexts/AuthContext';
type Row=Record<string,any>;
const labels:Record<string,string>={not_ordered:'Not yet ordered',pending:'Pending / In progress',not_approved:'Not yet approved',approved:'Approved'};
const threadLabels:Record<string,string>={not_ordered:'Not yet ordered',pending:'Ordered / Pending',not_approved:'Awaiting receipt',approved:'Received'};
const groups=[{key:'pattern',name:'Pattern',keys:['pattern']},{key:'fabric',name:'Fabric Approval',keys:['matching','printing','dyeing']},{key:'bulk',name:'Bulk Production Approval',keys:['bulk']},{key:'photoshoot',name:'Photoshoot Sample',keys:['photoshoot']},{key:'pp',name:'PP',keys:['pp']}];
function ApprovalRemarks({job,group,rows,error,threadOnly}:{job:Row;group:typeof groups[number];rows:Row[];error?:string;threadOnly:boolean}){
 const keys=group.keys.join(',');
 const loadHistory=useCallback(async()=>{
  const funcs=threadOnly?['erp_job_approval_audit']:['erp_component_approval_audit','erp_job_approval_audit'];
  const results=await Promise.all(funcs.map(f=>createClient().rpc(f,{p_job:job.id})));
  const failure=results.find(r=>r.error)?.error;if(failure)throw failure;
  return results.flatMap(r=>r.data||[]).filter((r:Row)=>keys.split(',').includes(r.stage));
 },[job.id,keys,threadOnly]);
 return <StageRemarksButton title={`${job.job_card_no} · ${group.name}`} rows={rows} error={error} loadHistory={loadHistory}/>;
}
export default function JobApprovalStages({job,report,error,onSaved,threadOnly=false}:{threadOnly?:boolean;job:Row;report?:Row;error?:string;onSaved:()=>void}){
 const {can}=useAuth();const [open,setOpen]=useState<string|null>(null),[draft,setDraft]=useState<Record<string,Row>>({}),[history,setHistory]=useState<Row[]>([]),[historyError,setHistoryError]=useState(''),[saving,setSaving]=useState(false),[failure,setFailure]=useState('');
 const saveLock=useRef(false);const [notice,setNotice]=useState('');
 const components:Row[]=report?.approval_components||[];
 const componentApprovals:Row[]=report?.component_approvals||[];
 const shownGroups=threadOnly?[{key:'thread',name:'Thread',keys:['thread']}]:groups;
 const statusLabels=threadOnly?threadLabels:labels;
 const approvals=report?.approvals||[];
 function begin(key:string){setNotice('');setDraft(Object.fromEntries((threadOnly?approvals:componentApprovals).map((a:Row)=>[threadOnly?a.stage:a.component_id+':'+a.stage,{...a}])));setFailure('');setOpen(key);}
 useEffect(()=>{if(!open)return;let alive=true;setHistory([]);setHistoryError('');Promise.all([createClient().rpc(threadOnly?'erp_job_approval_audit':'erp_component_approval_audit',{p_job:job.id}),threadOnly?Promise.resolve({data:[],error:null}):createClient().rpc('erp_job_approval_audit',{p_job:job.id})]).then(([current,legacy])=>{if(alive){setHistory([...(current.data||[]),...(legacy.data||[]).map((h:Row)=>({...h,component_name:'Previous Job Card-level approval'}))]);setHistoryError(current.error?.message||legacy.error?.message||'');}});return()=>{alive=false;};},[open,report,job.id]);
 async function save(key:string,componentId?:string){
  if(saveLock.current)return;saveLock.current=true;setSaving(true);setFailure('');setNotice('');
  const draftKey=componentId?componentId+':'+key:key;const d=draft[draftKey]||{status:'not_ordered',remarks:'',version:0};
  try{const client=createClient();const args={p_job:job.id,p_stage:key,p_status:d.status,p_remarks:d.remarks||'',p_version:d.version||0};
   const {data,error}=componentId?await client.rpc('erp_save_component_approval',{...args,p_component:componentId}):await client.rpc('erp_save_job_approval',args);
   if(error)throw error;if(componentId&&(!data||data.component_id!==componentId||data.stage!==key))throw new Error('Database save could not be confirmed.');
   if(componentId){setDraft(v=>({...v,[draftKey]:data}));setNotice(`${components.find(c=>c.id===componentId)?.name||'Component'} · ${key}: saved`);}else setOpen(null);onSaved();
  }catch(e){setFailure((e as Error).message);}finally{saveLock.current=false;setSaving(false);}
 }

 const group=shownGroups.find(g=>g.key===open);
 const bulkReceived=!threadOnly&&(report?.fabric||[]).some((r:Row)=>Number(r.received_qty??1)>0);
 return <>
 {!threadOnly&&<div className="min-w-[125px] flex-1 text-center"><Link href={`/production-batch/${job.id}`} className="min-w-[125px] flex-1 p-2 text-center rounded-lg hover:bg-slate-50"><span className="block mx-auto w-6 h-6 rounded-full border-2 border-green-600 bg-green-500">✓</span><span className="block text-xs font-semibold mt-2">Job Card</span><span className="block text-[11px]">Created</span></Link><StageRemarksButton title={`${job.job_card_no} · Job Card`} rows={[job]}/></div>}
 {shownGroups.map(g=>{const expected=threadOnly?g.keys:components.flatMap(c=>g.keys.map(k=>c.id+':'+k));const source=threadOnly?approvals:componentApprovals;const {done,partial,active}=componentApprovalStatus(expected,source.map((a:Row)=>({key:threadOnly?a.stage:a.component_id+':'+a.stage,status:a.status})));const isBulk=g.key==='bulk';const bulkApprovalDone=isBulk&&done;const bulkMainDone=isBulk?bulkReceived&&bulkApprovalDone:done;const bulkMainActive=isBulk?(bulkReceived&&!bulkApprovalDone)||partial||active:active||partial;return <div key={g.key} className="min-w-[125px] flex-1 text-center"><button onClick={()=>begin(g.key)} className="min-w-[125px] flex-1 p-2 text-center rounded-lg hover:bg-slate-50"><span className={`block mx-auto w-6 h-6 rounded-full border-2 ${error?'border-slate-400':bulkMainDone?'bg-green-500 border-green-600':bulkMainActive?'bg-orange-400 border-orange-500':'border-slate-300'}`}>{bulkMainDone&&!error?'✓':done&&!error&&!isBulk?'✓':''}</span><span className="block text-xs font-semibold mt-2">{g.name}</span>{isBulk&&!threadOnly?<div className="flex justify-center gap-2 mt-2"><span className={`text-[10px] px-2 py-0.5 rounded-full border ${bulkReceived?'bg-green-50 border-green-300 text-green-700':'border-slate-300 text-slate-500'}`}>{bulkReceived?'✓ ':'○ '}Received</span><span className={`text-[10px] px-2 py-0.5 rounded-full border ${bulkApprovalDone?'bg-green-50 border-green-300 text-green-700':bulkReceived?'bg-orange-50 border-orange-300 text-orange-700':'border-slate-300 text-slate-500'}`}>{bulkApprovalDone?'✓ ':'○ '}Approval</span></div>:<span className="block text-[11px] mt-1">{error?'Unavailable':done?(threadOnly?'Received':'Approved'):g.key==='fabric'&&(report?.fabric||[]).length?'Received · approval pending':!threadOnly&&!components.length?report?.component_link_error?'Item link needs review':'Components not configured':partial?'Partial':active?(threadOnly?'Ordered / Pending':'Pending approval'):'Not yet ordered'}</span>}</button><ApprovalRemarks job={job} group={g} rows={[...source,...(!threadOnly?approvals:[])].filter((a:Row)=>g.keys.includes(a.stage)).map((a:Row)=>({...a,component_name:a.component_name||components.find(c=>c.id===a.component_id)?.name}))} error={error} threadOnly={threadOnly}/></div>})}
 {group&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-3" onClick={()=>!saving&&setOpen(null)}><section role="dialog" aria-modal="true" aria-label={group.name} className="bg-white rounded-xl p-5 w-full max-w-2xl max-h-[85vh] overflow-auto" onClick={e=>e.stopPropagation()}><button className="float-right btn-secondary" disabled={saving} onClick={()=>setOpen(null)}>Close</button><h2 className="font-semibold">{job.job_card_no} · {group.name}</h2>{error?<p role="alert" className="text-red-600 my-4">Reporting unavailable: {error}</p>:<>
 {group.key==='fabric'&&<div className="border rounded-lg p-3 my-4"><h3 className="font-semibold">Linked fabric receipts</h3>{!(report?.fabric||[]).length?<p>No receipt linked to this Job Card. Receive or link the fabric entry to this Job Card in Fabric Inventory.</p>:(report?.fabric||[]).map((r:Row)=><p key={r.id} className="text-sm my-2">{r.receipt_no} · {r.processed_fabric_name||r.fabric_name} · {r.processing_type||'Process not specified'}: {r.received_qty==null?'Received — shared receipt; allocation quantity needs verification':`${r.received_qty} ${r.unit||''} received`}</p>)}<p className="text-xs mt-2 text-slate-600">Receipt and approval are separate. A complete/partial delivery cannot be certified until a Job Card fabric requirement is recorded. Only explicitly linked receipts are shown.</p></div>}
 {!can('jobs','edit')&&<p role="status" className="my-3 p-3 rounded-lg bg-amber-50 text-amber-900 text-sm">आपके user को Job Cards में Edit permission नहीं है। Status बदलने के लिए Owner से Users &amp; Access में यह अधिकार दिलवाएँ।</p>}
 {!threadOnly&&!components.length&&<p role="status" className="my-4">{report?.component_link_error||'No active components were found in the linked Item Master. Check its component setup before recording approvals.'}</p>}
 {!threadOnly&&approvals.some((a:Row)=>group.keys.includes(a.stage))&&<p className="text-sm my-3 text-amber-800">An earlier Job Card-level approval exists. Review each component individually; it has not been automatically applied to all components.</p>}
 {(threadOnly?[{id:'',name:'Thread'}]:components).map(component=><section key={component.id} className="my-4">{!threadOnly&&<h3 className="font-semibold text-primary">{component.name}</h3>}{group.keys.map(key=>{const draftKey=component.id?component.id+':'+key:key;const d=draft[draftKey]||{status:'not_ordered',remarks:'',version:0};return <div key={key} className="border rounded-lg p-3 my-3"><h3 className="capitalize font-semibold">{key==='bulk'?'Bulk Production':key==='pp'?'PP':key==='photoshoot'?'Photoshoot Sample':key}</h3><label className="block text-sm mt-2">{threadOnly?'Thread status':'Approval status'}<SearchableSelect disabled={!can('jobs','edit')||saving} className="block w-full border rounded p-2" value={d.status} onChange={e=>setDraft(v=>({...v,[draftKey]:{...d,status:e.target.value}}))}>{Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</SearchableSelect></label><label className="block text-sm mt-2">Remarks<textarea maxLength={2000} disabled={!can('jobs','edit')||saving} className="block w-full border rounded p-2" value={d.remarks} onChange={e=>setDraft(v=>({...v,[draftKey]:{...d,remarks:e.target.value}}))}/></label>{d.updated_at&&<p className="text-xs my-2">Updated {new Date(d.updated_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</p>}{can('jobs','edit')&&<button className="btn-primary mt-2" disabled={saving} onClick={()=>void save(key,component.id||undefined)}>{saving?'Saving…':'Save '+(key==='pp'?'PP':key==='photoshoot'?'Photoshoot Sample':key)}</button>}</div>})}</section>)}
 {!can('jobs','edit')&&<p className="text-sm">View only. Job Card edit permission is required to change approvals.</p>}
 </>}{notice&&<p role="status" className="text-green-700">{notice}</p>}{failure&&<p role="alert" className="text-red-600">{failure}</p>}<details className="mt-4"><summary>Entry history</summary>{historyError?<p role="alert">History unavailable: {historyError}</p>:history.filter(h=>group.keys.includes(h.stage)).map(h=><p key={h.id} className="text-sm border-t py-2">{h.component_name?`${h.component_name} · `:''}{h.stage}: {statusLabels[h.old_status]||'Not recorded'} → {statusLabels[h.new_status]} · {h.actor_name} · {new Date(h.changed_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST<br/>{h.remarks}</p>)}</details></section></div>}
 </>;
}
