'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';
import {useAuth} from '@/contexts/AuthContext';
type Row=Record<string,any>;
const labels:Record<string,string>={not_ordered:'Not yet ordered',pending:'Pending / In progress',not_approved:'Not yet approved',approved:'Approved'};
const groups=[{key:'pattern',name:'Pattern',keys:['pattern']},{key:'fabric',name:'Fabric Approval',keys:['matching','printing','dyeing']},{key:'bulk',name:'Bulk Production Approval',keys:['bulk']},{key:'pp',name:'PP',keys:['pp']}];
export default function JobApprovalStages({job,report,error,onSaved}:{job:Row;report?:Row;error?:string;onSaved:()=>void}){
 const {can}=useAuth();const [open,setOpen]=useState<string|null>(null),[draft,setDraft]=useState<Record<string,Row>>({}),[history,setHistory]=useState<Row[]>([]),[historyError,setHistoryError]=useState(''),[saving,setSaving]=useState(false),[failure,setFailure]=useState('');
 const approvals=report?.approvals||[];
 function begin(key:string){setDraft(Object.fromEntries(approvals.map((a:Row)=>[a.stage,{...a}])));setFailure('');setOpen(key);}
 useEffect(()=>{if(!open)return;let alive=true;setHistory([]);setHistoryError('');createClient().rpc('erp_job_approval_audit',{p_job:job.id}).then(({data,error})=>{if(alive){setHistory(data||[]);setHistoryError(error?.message||'');}});return()=>{alive=false;};},[open,report,job.id]);
 async function save(key:string){if(saving)return;setSaving(true);setFailure('');const d=draft[key]||{status:'not_ordered',remarks:'',version:0};try{const {error}=await createClient().rpc('erp_save_job_approval',{p_job:job.id,p_stage:key,p_status:d.status,p_remarks:d.remarks||'',p_version:d.version||0});if(error)throw error;setOpen(null);onSaved();window.dispatchEvent(new Event('erp-data-changed'));}catch(e){setFailure((e as Error).message);}finally{setSaving(false);}}
 const group=groups.find(g=>g.key===open);
 return <>
 <Link href={`/production-batch/${job.id}`} className="min-w-[125px] flex-1 p-2 text-center rounded-lg hover:bg-slate-50"><span className="block mx-auto w-6 h-6 rounded-full border-2 border-green-600 bg-green-500">✓</span><span className="block text-xs font-semibold mt-2">Job Card</span><span className="block text-[11px]">Created</span></Link>
 {groups.map(g=>{const done=g.keys.every(k=>approvals.some((a:Row)=>a.stage===k&&a.status==='approved'));const active=g.keys.some(k=>approvals.some((a:Row)=>a.stage===k&&a.status!=='not_ordered'));return <button key={g.key} onClick={()=>begin(g.key)} className="min-w-[125px] flex-1 p-2 text-center rounded-lg hover:bg-slate-50"><span className={`block mx-auto w-6 h-6 rounded-full border-2 ${error?'border-slate-400':done?'bg-green-500 border-green-600':active?'bg-orange-400 border-orange-500':'border-slate-300'}`}>{done&&!error?'✓':''}</span><span className="block text-xs font-semibold mt-2">{g.name}</span><span className="block text-[11px]">{error?'Unavailable':done?'Approved':g.key==='fabric'&&(report?.fabric||[]).length?'Received · approval pending':active?'Pending approval':'Not yet ordered'}</span></button>})}
 {group&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-3" onClick={()=>!saving&&setOpen(null)}><section role="dialog" aria-modal="true" aria-label={group.name} className="bg-white rounded-xl p-5 w-full max-w-2xl max-h-[85vh] overflow-auto" onClick={e=>e.stopPropagation()}><button className="float-right btn-secondary" disabled={saving} onClick={()=>setOpen(null)}>Close</button><h2 className="font-semibold">{job.job_card_no} · {group.name}</h2>{error?<p role="alert" className="text-red-600 my-4">Reporting unavailable: {error}</p>:<>
 {group.key==='fabric'&&<div className="border rounded-lg p-3 my-4"><h3 className="font-semibold">Linked fabric receipts</h3>{!(report?.fabric||[]).length?<p>No receipt linked to this Job Card. Receive or link the fabric entry to this Job Card in Fabric Inventory.</p>:(report?.fabric||[]).map((r:Row)=><p key={r.id} className="text-sm my-2">{r.receipt_no} · {r.processed_fabric_name||r.fabric_name} · {r.processing_type||'Process not specified'}: {r.received_qty==null?'Received — shared receipt; allocation quantity needs verification':`${r.received_qty} ${r.unit||''} received`}</p>)}<p className="text-xs mt-2 text-slate-600">Receipt and approval are separate. A complete/partial delivery cannot be certified until a Job Card fabric requirement is recorded. Only explicitly linked receipts are shown.</p></div>}
 {group.keys.map(key=>{const d=draft[key]||{status:'not_ordered',remarks:'',version:0};return <div key={key} className="border rounded-lg p-3 my-3"><h3 className="capitalize font-semibold">{key==='bulk'?'Bulk Production':key==='pp'?'PP':key}</h3><label className="block text-sm mt-2">Approval status<select disabled={!can('jobs','edit')||saving} className="block w-full border rounded p-2" value={d.status} onChange={e=>setDraft(v=>({...v,[key]:{...d,status:e.target.value}}))}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="block text-sm mt-2">Remarks<textarea maxLength={2000} disabled={!can('jobs','edit')||saving} className="block w-full border rounded p-2" value={d.remarks} onChange={e=>setDraft(v=>({...v,[key]:{...d,remarks:e.target.value}}))}/></label>{d.updated_at&&<p className="text-xs my-2">Updated {new Date(d.updated_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</p>}{can('jobs','edit')&&<button className="btn-primary mt-2" disabled={saving} onClick={()=>void save(key)}>{saving?'Saving…':'Save '+(key==='pp'?'PP':key)}</button>}</div>})}
 {!can('jobs','edit')&&<p className="text-sm">View only. Job Card edit permission is required to change approvals.</p>}
 </>}{failure&&<p role="alert" className="text-red-600">{failure}</p>}<details className="mt-4"><summary>Entry history</summary>{historyError?<p role="alert">History unavailable: {historyError}</p>:history.filter(h=>group.keys.includes(h.stage)).map(h=><p key={h.id} className="text-sm border-t py-2">{h.stage}: {labels[h.old_status]||'Not recorded'} → {labels[h.new_status]} · {h.actor_name} · {new Date(h.changed_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST<br/>{h.remarks}</p>)}</details></section></div>}
 </>;
}
