'use client';
import {useEffect,useState,useRef} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';
import {useAuth} from '@/contexts/AuthContext';
import {automaticOrderOverview,orderComponentBreakdown} from '@/lib/automaticOrderOverview';
type Row=Record<string,any>;
export default function OrderQuantityOverview({refresh}:{refresh:string}){
 const loaded=useRef(false);
 const {can,accessProfile}=useAuth();const [rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[mode,setMode]=useState<'active'|'pending'>('active'),[open,setOpen]=useState(false);
 useEffect(()=>{if(!can('sales'))return;let alive=true;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),25000);if(!loaded.current)setLoading(true);setError('');
 async function load(){try{const snapshots:Row[]=[];for(let offset=0;;offset+=100){const {data,error}=await createClient().rpc('erp_order_linked_report',{p_offset:offset,p_limit:100}).abortSignal(controller.signal);if(error)throw error;snapshots.push(...data||[]);if(!data||data.length<100)break;}if(alive){loaded.current=true;setRows(automaticOrderOverview(snapshots));};}catch(e){if(alive)setError(controller.signal.aborted?'Report took too long to load. Refresh to retry.':(e as Error).message);}finally{clearTimeout(timer);if(alive)setLoading(false);}}
 void load();return()=>{alive=false;clearTimeout(timer);controller.abort();};},[refresh,can,accessProfile?.user_id]);
 useEffect(()=>{if(!open)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[open]);
 if(!can('sales'))return null;
 const componentBreakdown=orderComponentBreakdown(rows,mode);
 const fields=mode==='active'?['quantity','components']:['pending','pendingComponents'];
 return <><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{['Order Quantity','Sub-component Quantity'].map((title,i)=>{const field=fields[i],missing=rows.filter(r=>r[field]==null||!Number.isFinite(r[field]));const known=rows.reduce((n,r)=>n+(Number.isFinite(r[field])?r[field]:0),0);return <section key={title} className="card-surface p-5"><div className="flex flex-wrap justify-between items-center gap-3"><h2 className="section-label">{title}</h2><div className="flex bg-muted rounded-full p-1">{(['active','pending'] as const).map(m=><button key={m} aria-pressed={mode===m} onClick={()=>setMode(m)} className={`px-3 py-1 rounded-full text-xs ${mode===m?'bg-primary text-white':''}`}>{m==='active'?'Active':'Pending'}</button>)}</div></div><button className="block text-left w-full mt-4 hover:text-primary" onClick={()=>setOpen(true)}><strong className="text-3xl">{loading||error?'—':known.toLocaleString('en-IN')}</strong><p className="text-sm text-muted-foreground mt-2">{mode==='active'?'Total ordered':'Not covered by complete cut sets'} · {i?'sub-components':'main pieces / sets'}{missing.length?' · partial total':''}</p><p className="text-xs text-primary mt-2">{error?'Report unavailable · view details':missing.length?`${missing.length} item groups need source details · View reasons`:'View linked vouchers and calculation →'}</p></button>{i===1&&!loading&&!error&&<div className="mt-4 border-t border-border pt-4"><p className="text-xs text-muted-foreground mb-3">{mode==='active'?'Ordered components':'Pending components · complete-set basis'}{missing.length?' · known quantities only':''}</p>{componentBreakdown.length?<dl className="grid grid-cols-2 xl:grid-cols-3 gap-2">{componentBreakdown.map(part=><div key={part.name} className="rounded-lg bg-muted/50 px-3 py-2 min-w-0"><dt className="text-sm capitalize break-words">{part.name}</dt><dd className="font-semibold tabular-nums mt-1">{part.quantity.toLocaleString('en-IN')} <span className="text-xs font-normal text-muted-foreground">pcs</span></dd></div>)}</dl>:<p className="text-sm text-muted-foreground">{missing.length?'Component details unavailable for these items.':'No components in this report.'}</p>}</div>}</section>;})}</div>{error&&<p role="alert" className="text-amber-700 text-sm">Order overview unavailable: {error}</p>}
 {open&&<div className="erp-modal-enter fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><section role="dialog" aria-modal="true" aria-label="Automatic order quantity details" className="bg-white rounded-xl p-5 w-full max-w-5xl max-h-[85vh] overflow-auto"><button autoFocus className="float-right btn-secondary" onClick={()=>setOpen(false)}>Close</button><h2 className="font-semibold">Automatic order quantity breakdown</h2><p className="text-sm text-muted-foreground my-3">Sales Order → Job Card → net Cutting vouchers. Size lines are grouped by item and colour. Complete cut sets require every component in the Item Master composition; surplus in one component cannot cover another. Fabric metres are not treated as garment pieces. No manual confirmation is required.</p>{loading?<p role="status">Loading linked quantities…</p>:error?<p role="alert">{error}</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left"><th>Order / Item</th><th>Ordered</th><th>Complete cut sets</th><th>Pending</th><th>Components / set</th><th>Ordered components</th><th>Pending components</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="py-3 pr-3"><p>{r.order_no} · {r.party}</p>{r.styleId&&can('items')?<Link className="text-primary" href={`/item-master?styleId=${r.styleId}`}>{r.item}</Link>:r.item} {r.colour&&<span>· {r.colour}</span>}<div className="text-xs my-2">{r.jobs.map((j:Row)=><span key={j.id} className="block">{can('jobs')?<Link className="text-primary" href={`/production-batch/${j.id}`}>{j.job_card_no}</Link>:j.job_card_no}</span>)}<p>Cutting vouchers: {r.vouchers.join(', ')||'None linked'}</p></div>{r.problem&&<div role="alert" className="text-amber-700 text-xs max-w-xs space-y-2">{(r.problems||[]).map((p:Row,i:number)=><p key={i}>{can(p.module)?<Link className="underline underline-offset-2" href={p.href}>{p.message} → Open correction screen</Link>:<>{p.message}<span className="block">Ask a user with access to {p.module} to correct this record.</span></>}</p>)}</div>}</td><td>{r.quantity}</td><td>{r.ready??'—'}</td><td>{r.pending??'Unknown'}</td><td>{r.ratio??'—'}</td><td>{r.components??'—'}</td><td>{r.pendingComponents??'Unknown'}</td></tr>)}</tbody></table></div>}</section></div>}</>;
}
