'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';
import {useAuth} from '@/contexts/AuthContext';
import {orderOverview} from '@/lib/orderOverview';
type Row=Record<string,any>;
async function all(table:string){let rows:Row[]=[];const db=createClient();for(let start=0;;start+=500){const {data,error}=await db.from(table).select('*').order(table==='erp_order_readiness'?'order_item_id':'id').range(start,start+499);if(error)throw Error(error.message);rows.push(...data||[]);if(!data||data.length<500)return rows;}}
export default function OrderQuantityOverview({refresh}:{refresh:string}){
 const {can,accessProfile}=useAuth();const [rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0),[mode,setMode]=useState<'active'|'pending'>('active'),[open,setOpen]=useState(false),[edit,setEdit]=useState<Row|null>(null),[qty,setQty]=useState(''),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState('');
 useEffect(()=>{let alive=true;setLoading(true);setRows([]);setError('');if(!can('sales')){setLoading(false);return;}const tables=['sales_orders','sales_order_items',...(can('items')?['item_styles','item_compositions']:[]),'erp_order_readiness'];Promise.all(tables.map(async t=>[t,await all(t)] as const)).then(entries=>{if(!alive)return;const d=Object.fromEntries(entries);setRows(orderOverview(d.sales_orders,d.sales_order_items,d.item_styles||[],d.item_compositions||[],d.erp_order_readiness));}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[refresh,revision,can,accessProfile?.user_id]);
 useEffect(()=>{if(!open)return;const f=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);setEdit(null);}};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f);},[open]);
 async function save(){if(!edit)return;setSaving(true);setSaveError('');const {error}=await createClient().rpc('erp_save_order_readiness',{p_item:edit.id,p_qty:Number(qty)});setSaving(false);if(error)setSaveError(error.message);else{setEdit(null);setRevision(v=>v+1);}}
 if(!can('sales'))return null;
 const fields=mode==='active'?['quantity','components']:['pending','pendingComponents'];
 return <><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{['Order Quantity','Sub-component Quantity'].map((title,i)=>{const field=fields[i],missing=rows.filter(r=>r[field]===null||!Number.isFinite(r[field]));return <section key={title} className="card-surface p-5"><div className="flex flex-wrap justify-between items-center gap-3"><h2 className="section-label">{title}</h2><div className="flex bg-muted rounded-full p-1">{(['active','pending'] as const).map(m=><button key={m} aria-pressed={mode===m} onClick={()=>setMode(m)} className={`px-3 py-1 rounded-full text-xs ${mode===m?'bg-primary text-white':''}`}>{m==='active'?'Active':'Pending'}</button>)}</div></div><button className="block text-left w-full mt-4 hover:text-primary" onClick={()=>setOpen(true)}><strong className="text-3xl">{loading||error?'—':missing.length?'Needs confirmation':rows.reduce((n,r)=>n+Number(r[field]),0).toLocaleString('en-IN')}</strong><p className="text-sm text-muted-foreground mt-2">{mode==='active'?'Total ordered':'Not fabric-ready / not started'} · {i?'required sub-components':'main pieces / sets'}</p><p className="text-xs text-primary mt-2">{missing.length?`${missing.length} entries need ${i&&mode==='active'?'composition':'confirmation'} · View details`:'View item-wise calculation →'}</p></button></section>;})}</div>{error&&<p role="alert" className="text-amber-700 text-sm">Order overview unavailable: {error}</p>}
 {open&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><section role="dialog" aria-modal="true" aria-label="Order quantity details" className="bg-white rounded-xl p-5 w-full max-w-5xl max-h-[85vh] overflow-auto"><button autoFocus className="float-right btn-secondary" onClick={()=>{setOpen(false);setEdit(null);}}>Close</button><h2 className="font-semibold">Order quantity breakdown</h2><p className="text-sm text-muted-foreground my-3">Ready/started means the total order quantity with fabric available OR processing started. Count each piece once. Pending is part of the Active total.</p>{loading?<p>Loading…</p>:<table className="w-full text-sm"><thead><tr className="text-left"><th>Order / Item</th><th>Active</th><th>Ready / started</th><th>Pending</th><th>Components / item</th><th>Required</th><th>Pending components</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="py-3 pr-3"><p>{r.order_no} · {r.party}</p>{r.styleId&&can('items')?<Link className="text-primary" href={`/item-master?styleId=${r.styleId}`}>{r.item}</Link>:r.item}<p className="text-xs text-muted-foreground">{r.composition}</p>{r.problem&&<p className="text-amber-700 text-xs">{r.problem}</p>}</td><td>{r.quantity}</td><td><button disabled={!can('sales','edit')||r.uneditable} onClick={()=>{setEdit(r);setQty(String(r.ready??0));setSaveError('');}} className="text-primary underline">{r.ready??'Confirm'} {can('sales','edit')&&!r.uneditable?'✎':''}</button></td><td>{r.pending??'—'}</td><td>{r.ratio??'—'}</td><td>{r.components??'—'}</td><td>{r.pendingComponents??'—'}</td></tr>)}</tbody></table>}{edit&&<div className="border rounded-lg p-4 mt-4"><p className="font-semibold">{edit.item} · {edit.quantity} ordered</p><label className="block my-2">Total fabric-ready / process-started quantity <input type="number" min="0" max={edit.quantity} step="1" value={qty} onChange={e=>setQty(e.target.value)} className="border rounded p-2 w-28"/></label><p className="text-xs mb-3">Include both categories without counting the same quantity twice. Enter 0 to confirm none is ready.</p><button onClick={()=>void save()} disabled={saving||qty===''||!Number.isInteger(Number(qty))||Number(qty)<0||Number(qty)>edit.quantity} className="btn-primary">{saving?'Saving…':'Save'}</button><button onClick={()=>setEdit(null)} className="btn-secondary ml-2">Cancel</button>{saveError&&<p role="alert" className="text-red-600">{saveError}</p>}</div>}</section></div>}</>;
}
