'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';
import {useAuth} from '@/contexts/AuthContext';
import {progressState,componentKey,processProgress} from '@/lib/dashboardProgress';
type Row=Record<string,any>;
type Stage={name:string;module:string;headers:string;children?:string;parent?:string;component?:string;quantity:string;unit:string;issues?:string;process?:string};
const stages:Stage[]=[
 {name:'Cutting',module:'cutting',headers:'cutting_entries',children:'cutting_sub_components',parent:'cutting_entry_id',component:'component',quantity:'net_pieces',unit:'sub-components'},
 {name:'Embroidery',module:'embroidery',headers:'emb_receive_vouchers',issues:'emb_issue_vouchers',process:'embroidery',component:'component',quantity:'quantity',unit:'',},
 {name:'Handwork',module:'handwork',headers:'emb_receive_vouchers',issues:'emb_issue_vouchers',process:'handwork',component:'component',quantity:'quantity',unit:'',},
 {name:'Stitching',issues:'stitch_issue_vouchers',module:'stitching',headers:'stitch_receive_vouchers',children:'stitch_receive_components',parent:'receive_voucher_id',component:'component',quantity:'received_qty',unit:'sub-components'},
 {name:'QC',module:'qc',headers:'qc_entries',children:'qc_sub_components',parent:'qc_entry_id',component:'component',quantity:'pass_count',unit:'sub-components'},
 {name:'Contractor Finishing',issues:'contractor_issue_vouchers',module:'contractor',headers:'contractor_receive_vouchers',children:'contractor_receive_items',parent:'receive_voucher_id',component:'item',quantity:'received_today',unit:'sub-components'},
 {name:'Assembly',module:'contractor',headers:'component_assembly_vouchers',quantity:'total_sets_assembled',unit:'ready items'},
 {name:'Dispatch',module:'dispatch',headers:'dispatch_vouchers',quantity:'dispatched_pieces',unit:'ready items'},
];
const colors={complete:'bg-green-500 border-green-600',active:'bg-orange-400 border-orange-500',stalled:'bg-red-500 border-red-600',empty:'bg-white border-slate-300',unknown:'bg-orange-100 border-orange-400'};
const baseNames={complete:'Completed',active:'In progress',stalled:'No activity · 3+ days',empty:'Not started',unknown:'Check target / date'};
async function readTable(table:string){const db=createClient();const rows:Row[]=[];for(let i=0;;i+=500){const {data,error}=await db.from(table).select('*').order('id').range(i,i+499);if(error)throw Error(error.message);rows.push(...data||[]);if(!data||data.length<500)return rows;}}
export default function ProductionJourney({jobs,refresh}:{jobs:Row[];refresh:string}){
 const [inactivityDays,setInactivityDays]=useState<number|null>(null),[settingsError,setSettingsError]=useState('');
 const names={...baseNames,stalled:`No activity · ${inactivityDays??'?'}+ days`};
 const {can,accessProfile}=useAuth();const [tables,setTables]=useState<Record<string,Row[]>>({}),[errors,setErrors]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true);
 const [search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[detail,setDetail]=useState<{job:Row;stage:Stage;rows:Row[];required:Row;received:Row;last:string;error?:string}|null>(null);
 useEffect(()=>{let alive=true;setLoading(true);const allowed=stages.filter(s=>can(s.module));const tableNames=Array.from(new Set([...allowed.flatMap(s=>[s.headers,...s.children?[s.children]:[],...s.issues?[s.issues]:[]]),...(can('items')?['item_styles','item_compositions']:[])]));
 Promise.all(tableNames.map(async t=>{try{return {t,rows:await readTable(t),error:''};}catch(e){return {t,rows:[],error:(e as Error).message};}})).then(results=>{if(!alive)return;setTables(Object.fromEntries(results.map(r=>[r.t,r.rows])));setErrors(Object.fromEntries(results.filter(r=>r.error).map(r=>[r.t,r.error])));setLoading(false);});return()=>{alive=false;};},[refresh,can,accessProfile?.user_id]);
 useEffect(()=>{let alive=true;createClient().from('erp_dashboard_settings').select('inactivity_days').eq('id',1).single().then(({data,error})=>{if(!alive)return;if(error){setInactivityDays(null);setSettingsError('Shared inactivity settings unavailable. Red inactivity alerts are paused until settings load.');}else{setInactivityDays(data.inactivity_days);setSettingsError('');}});return()=>{alive=false;};},[refresh,accessProfile?.user_id]);
 useEffect(()=>{if(!detail)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setDetail(null);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[detail]);
 useEffect(()=>{try{const saved=JSON.parse(sessionStorage.getItem('dashboard-filter:'+accessProfile?.user_id)||'null');if(saved){setSearch(saved.search||'');setFilter(saved.filter||'all');}}catch{}},[accessProfile?.user_id]);
 useEffect(()=>{try{sessionStorage.setItem('dashboard-filter:'+accessProfile?.user_id,JSON.stringify({search,filter}));}catch{}},[search,filter,accessProfile?.user_id]);
 function station(job:Row,stage:Stage){
  if(stage.process){const p=processProgress(tables.emb_issue_vouchers||[],tables.emb_receive_vouchers||[],{id:job.id,job_card_no:job.job_card_no},stage.process);return {job,stage,rows:[...p.rows,...p.issues.map(v=>({voucher_no:v.voucher_no,voucher_date:v.voucher_date,entry_type:'Issue',cutting_items:v.cutting_items,fabric_items:v.fabric_items,accessory_items:v.accessory_items}))],required:p.required,received:p.received,last:p.last,error:errors.emb_issue_vouchers||errors.emb_receive_vouchers||p.problem,state:progressState(p.required,p.received,p.started,p.last,Date.now(),inactivityDays??Infinity)};}

  const headers=(tables[stage.headers]||[]).filter(r=>(r.job_card_ref===job.job_card_no||r.job_card_id===job.id)&&r.status!=='cancelled'&&(stage.name!=='Dispatch'||r.style_name===job.style_en)&&(stage.name!=='Assembly'||r.assembly_kind!=='component_conversion'));
  const activity=[...headers,...(tables[stage.issues||'']||[]).filter(r=>r.job_card_ref===job.job_card_no&&r.status!=='cancelled')];
  const ids=new Set(headers.map(r=>r.id));const rows:Row[]=stage.children?(tables[stage.children]||[]).filter(r=>ids.has(r[stage.parent!])).map(r=>{const header=headers.find(h=>h.id===r[stage.parent!]);return {...r,voucher_no:header?.voucher_no||header?.entry_no,voucher_date:header?.voucher_date||header?.date};}):headers;
  const styles=tables.item_styles||[];let explicit=job.item_style_id?styles.filter(s=>s.id===job.item_style_id):styles.filter(s=>s.linked_job_card_id===job.id||s.job_card_no===job.job_card_no);
  if(!job.item_style_id&&!explicit.length)explicit=styles.filter(s=>(componentKey(job.style_en)&&componentKey(s.style_no)===componentKey(job.style_en))||(componentKey(job.design_code)&&componentKey(s.design_code)===componentKey(job.design_code)));
  const required:Row={},received:Row={};
  if(stage.children&&explicit.length===1){for(const c of (tables.item_compositions||[]).filter(r=>r.style_id===explicit[0].id)){const key=componentKey(c.component_name);if(key)required[key]=(required[key]||0)+Number(c.qty_per_set||0)*Number(job.total_pieces||0);}}
  if(!stage.children&&Number(job.total_pieces)>0)required['ready items']=Number(job.total_pieces);
  for(const r of rows){const key=stage.children?componentKey(r[stage.component!]):'ready items';received[key]=(received[key]||0)+Number(r[stage.quantity]||0);}
  const last=activity.map(r=>r.updated_at||r.created_at||r.voucher_date||r.dispatch_date||r.date||'').filter(Boolean).sort().at(-1)||'';
  const error=errors[stage.headers]||errors[stage.issues||'']||(stage.children?errors[stage.children]:undefined);
  return {job,stage,rows,required,received,last,error,state:progressState(required,received,activity.length>0,last,Date.now(),inactivityDays??Infinity)};
 }
 const visible=jobs.filter(j=>`${j.job_card_no} ${j.style_en} ${j.party_name}`.toLowerCase().includes(search.toLowerCase())).map(job=>({job,stations:stages.filter(s=>can(s.module)).map(s=>station(job,s))})).filter(({job,stations})=>filter==='all'||(filter==='attention'?(job.is_blocked||stations.some(s=>s.state==='stalled')):!['completed','dispatched','cancelled'].includes(job.stage)));
 return <section className="card-surface p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-700 text-lg">Item progress</h2><p className="text-sm text-muted-foreground">Tap a station for quantities and voucher details.</p></div><input aria-label="Search item or Job Card" className="border rounded-lg p-2 text-sm" placeholder="Search item / Job Card / party" value={search} onChange={e=>setSearch(e.target.value)}/></div>
 {settingsError&&<p role="alert" className="text-amber-700 text-sm mt-3">{settingsError}</p>}
 <div className="flex flex-wrap gap-4 text-xs my-4">{(['complete','active','stalled','empty'] as const).map(k=><span key={k} className="flex items-center gap-2"><span className={`w-3 h-3 rounded-full border ${colors[k]}`}/>{names[k]}</span>)}</div>
 <div className="flex gap-2 mb-4">{['all','active','attention'].map(f=><button key={f} onClick={()=>setFilter(f)} className={`rounded-full px-3 py-1 text-sm border ${filter===f?'bg-primary text-white':''}`}>{f==='attention'?'Needs attention':f==='all'?'All items':'Active items'}</button>)}</div>
 {loading?<p role="status">Loading production entries…</p>:<div className="space-y-4 max-h-[640px] overflow-auto">{visible.map(({job,stations})=><article key={job.id} className="border rounded-xl p-4"><div className="flex flex-wrap justify-between gap-2 mb-4"><div>{can('items')?<Link className="font-700 text-primary hover:underline" href={`/item-master?${job.item_style_id?'styleId='+encodeURIComponent(job.item_style_id):'search='+encodeURIComponent(job.style_en||job.job_card_no)}`}>{job.style_en||job.job_card_no}</Link>:<span className="font-700">{job.style_en||job.job_card_no}</span>}<p className="text-xs text-muted-foreground"><Link href={`/production-batch/${job.id}`} className="hover:underline">{job.job_card_no}</Link> · {job.party_name}</p></div><span className="text-xs">{Number(job.total_pieces||0).toLocaleString()} main pieces · Due {job.due_date||'—'}</span></div>
 <div className="flex overflow-x-auto pb-2">{stations.map(s=><button key={s.stage.name} onClick={()=>setDetail(s)} className="relative min-w-[125px] flex-1 text-center group p-2 rounded-lg hover:bg-slate-50 focus-visible:ring-2 focus-visible:ring-primary"><span className="absolute h-px bg-slate-200 top-5 left-0 right-0"/><span className={`relative block mx-auto w-6 h-6 rounded-full border-2 ${s.error?'bg-slate-100 border-slate-400':colors[s.state]}`}>{s.state==='complete'&&!s.error?'✓':''}</span><span className="block text-xs font-600 mt-2">{s.stage.name}</span><span className="block text-[11px] mt-1">{s.error?'Unavailable':names[s.state]}</span><span className="block text-[11px] text-muted-foreground">{s.error?'—':s.stage.process?`${Object.keys(s.required).filter(k=>(s.received[k]||0)>=s.required[k]).length} / ${Object.keys(s.required).length} issued lines done`:`${Object.values(s.received).reduce((a:number,b:any)=>a+Number(b),0)} / ${Object.keys(s.required).length?Object.values(s.required).reduce((a:number,b:any)=>a+Number(b),0):'?'}`}</span></button>)}</div>
 {job.is_blocked&&<p className="text-sm text-red-600 mt-2">Blocked: {job.blockage_reason_en||'Open Job Card for details'}</p>}</article>)}{!visible.length&&<p className="py-8 text-center text-muted-foreground">No matching items.</p>}</div>}
 <p className="text-xs text-muted-foreground mt-4">Embroidery/Handwork track the work issued to that process, with fabric and accessories kept in their own units. Their green status means all currently issued lines were received; further issues can reopen the stage. Quantities for other production stages are sub-components until assembly; assembly and dispatch count ready items. “?” means the required component plan is not available. Completion requires every planned component. Mixed-component new items are listed in Ready Items; they do not complete the original item’s assembly target.</p>
 {detail&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4" onClick={()=>setDetail(null)}><section role="dialog" aria-modal="true" aria-label="Stage details" className="bg-white rounded-xl p-5 w-full max-w-3xl max-h-[85vh] overflow-auto" onClick={e=>e.stopPropagation()}><button autoFocus className="float-right btn-secondary" onClick={()=>setDetail(null)}>Close</button><h2 className="font-700">{detail.job.job_card_no} · {detail.stage.name}</h2><p className="text-sm my-2">{detail.stage.process?"Target: work issued to this department. This does not certify completion of unissued work. ":""}Last activity: {detail.last||'No date recorded'}</p>{detail.error?<p role="alert">Could not load: {detail.error}</p>:<><table className="w-full text-sm my-4"><thead><tr><th className="text-left">Component / Item</th><th>Completed</th><th>Required</th><th>Pending</th></tr></thead><tbody>{Array.from(new Set([...Object.keys(detail.required),...Object.keys(detail.received)])).map(k=><tr key={k} className="border-t"><td className="py-2">{k}</td><td className="text-center">{detail.received[k]||0}</td><td className="text-center">{detail.required[k]??'Unknown'}</td><td className="text-center">{detail.required[k]?Math.max(0,detail.required[k]-(detail.received[k]||0)):'—'}</td></tr>)}</tbody></table><p className="font-600 text-sm">Source entries ({detail.rows.length})</p>{detail.rows.map((r,i)=><details key={r.id||i} className="border rounded-lg p-3 my-2"><summary className="cursor-pointer">{r.voucher_no||r.entry_no||r[detail.stage.component||'']||`Entry ${i+1}`} · {r.entry_type==='Issue'?'Issue':`${r[detail.stage.quantity]||0} ${r.unit||detail.stage.unit}`} </summary><dl className="grid grid-cols-2 gap-2 text-xs mt-3">{Object.entries(r).filter(([k,v])=>v!=null&&!k.endsWith('_id')&&k!=='id').map(([k,v])=><div key={k}><dt className="text-muted-foreground">{k.replaceAll('_',' ')}</dt><dd className="break-words">{typeof v==='object'?JSON.stringify(v):String(v)}</dd></div>)}</dl></details>)}</>}<Link href={`/production-batch/${detail.job.id}`} className="text-primary hover:underline">Open Job Card production detail →</Link></section></div>}
 </section>;
}
