'use client';
import {useEffect,useRef,useState} from 'react';
import SearchableSelect from '@/components/SearchableSelect';
import {useAuth} from '@/contexts/AuthContext';
import {createClient} from '@/lib/supabase/client';
type Row=Record<string,any>;
type Kind='account'|'operator'|'item';
function name(row:Row){return row.name||row.operator_name||row.item_name||row.style_no||row.job_card_no||row.id;}
function ChoiceValue({value}:{value:any}){
 if(value==null||value==='')return <span className="text-muted-foreground">Empty</span>;
 if(Array.isArray(value))return <div className="space-y-2">{value.map((v,i)=><div key={i} className="border-b pb-2"><ChoiceValue value={v}/></div>)}</div>;
 if(typeof value==='object')return <dl className="space-y-1">{Object.entries(value).filter(([k])=>!['id','style_id','variant_id','created_at','updated_at','created_by','updated_by','image_hash','import_key','import_batch_id','colour_normalized','component_name_normalized','material_name_normalized','source_row','source_row_start','source_row_end'].includes(k)).map(([k,v])=><div key={k}><dt className="text-muted-foreground">{k.replace(/_/g,' ')}</dt><dd className="break-words"><ChoiceValue value={v}/></dd></div>)}</dl>;
 if(typeof value==='string'&&/^https?:\/\//.test(value))return <a href={value} target="_blank" rel="noopener noreferrer" className="text-primary underline break-all" onClick={e=>e.stopPropagation()}>Open attachment ↗</a>;
 return <span className="break-words">{String(value)}</span>;
}
export default function MasterMerge(){
 const {accessProfile}=useAuth();const owner=!!accessProfile?.active&&!!accessProfile?.is_owner;
 const [open,setOpen]=useState(false),[kind,setKind]=useState<Kind>('account'),[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [sourceA,setA]=useState(''),[sourceB,setB]=useState(''),[newName,setName]=useState(''),[dr,setDr]=useState('0'),[cr,setCr]=useState('0'),[preview,setPreview]=useState<Row|null>(null),[reviewed,setReviewed]=useState(false),[confirm,setConfirm]=useState(''),[reload,setReload]=useState(0);
 const [choices,setChoices]=useState<Record<string,string>>({}),[choicesDirty,setChoicesDirty]=useState(false);
 const lock=useRef(false),request=useRef('');
 useEffect(()=>{if(!open||!owner)return;let alive=true;setLoading(true);setError('');setRows([]);Promise.resolve(createClient().rpc('erp_master_merge_options',{p_kind:kind})).then(({data,error})=>{if(!alive)return;if(error)setError(error.message);else setRows(data||[]);}).catch(e=>{if(alive)setError(e.message||'Could not load masters.');}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false};},[open,kind,reload,owner]);
 function invalidate(){setChoices({});setChoicesDirty(false);setPreview(null);setReviewed(false);setConfirm('');setError('');setNotice('');request.current='';}
 function choose(a:string,b:string){invalidate();setA(a);setB(b);const one=rows.find(r=>r.id===a),two=rows.find(r=>r.id===b);setDr((Number(one?.op_bal_dr||0)+Number(two?.op_bal_dr||0)).toFixed(2));setCr((Number(one?.op_bal_cr||0)+Number(two?.op_bal_cr||0)).toFixed(2));}
 async function inspect(){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');setPreview(null);setReviewed(false);setConfirm('');try{const {data,error}=await createClient().rpc('erp_master_merge_plan',{p_kind:kind,p_a:sourceA,p_b:sourceB,p_name:newName.trim(),p_dr:kind==='account'?Number(dr):null,p_cr:kind==='account'?Number(cr):null,p_choices:choices});if(error)throw error;if(!data?.token)throw Error('Merge preview was not returned.');setPreview(data);setChoicesDirty(false);request.current=crypto.randomUUID();}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 async function merge(){if(lock.current||!preview||choicesDirty||!reviewed||confirm!==preview.new_name)return;lock.current=true;setBusy(true);setError('');try{const {data,error}=await createClient().rpc('erp_merge_masters',{p_kind:kind,p_a:sourceA,p_b:sourceB,p_name:preview.new_name,p_dr:kind==='account'?Number(dr):null,p_cr:kind==='account'?Number(cr):null,p_token:preview.token,p_request:request.current,p_reviewed:reviewed,p_choices:preview.choices});if(error)throw error;if(data?.target_id!==sourceA||data?.request_id!==request.current)throw Error('Merge completion could not be confirmed. Keep this screen open and retry to check the same request.');setNotice(`Merged successfully into ${data.target_name}.`);setPreview(null);setChoices({});setChoicesDirty(false);setA('');setB('');setName('');setReviewed(false);setConfirm('');setReload(v=>v+1);}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 if(!owner)return null;
 const ready=!!sourceA&&!!sourceB&&sourceA!==sourceB&&!!newName.trim()&&(kind!=='account'||(dr!==''&&cr!==''&&Number.isFinite(Number(dr))&&Number.isFinite(Number(cr))));
 return <section className="card-surface border border-border rounded-xl p-4 space-y-4" aria-label="Master Merge">
  <button type="button" className="btn-secondary" disabled={busy} aria-expanded={open} onClick={()=>setOpen(v=>!v)}>Master Merge · Duplicate records</button>
  {open&&<><h2 className="text-lg font-semibold">Merge duplicate masters</h2><p className="text-sm text-muted-foreground">Choose two records and a new name. Source 1 is retained as the combined record; Source 2 and affected entries are preserved in merge history. Vouchers and quantities are not combined or deleted.</p>
  <fieldset disabled={busy||loading} className="space-y-4 min-w-0">
   <label className="block">Master type<SearchableSelect aria-label="Master type" className="input-field w-full" value={kind} onChange={e=>{invalidate();setKind(e.target.value as Kind);setA('');setB('');setName('');setDr('0');setCr('0');}}><option value="account">Account Master</option><option value="operator">Operator Master</option><option value="item">Item Master</option></SearchableSelect></label>
   <div className="grid sm:grid-cols-2 gap-4">{['Source 1','Source 2'].map((label,index)=><label className="block min-w-0" key={label}>{label}<SearchableSelect aria-label={label} className="input-field w-full" value={index?sourceB:sourceA} onChange={e=>index?choose(sourceA,e.target.value):choose(e.target.value,sourceB)}><option value="">Select existing record</option>{rows.filter(r=>r.id!==(index?sourceA:sourceB)).map(r=><option key={r.id} value={r.id}>{name(r)} · {r.operator_code||r.style_no||r.parent_group||r.id.slice(0,8)}</option>)}</SearchableSelect></label>)}</div>
   <label className="block">New merged name<input aria-label="New merged name" className="input-field w-full" maxLength={200} value={newName} onChange={e=>{invalidate();setName(e.target.value);}}/></label>
   {kind==='account'&&<div className="border border-border rounded-lg p-3 space-y-3"><p className="text-sm">Suggested opening balances add both sources. Review them: duplicate balances must not be counted twice. Transaction amounts stay unchanged.</p><div className="grid sm:grid-cols-2 gap-3"><label>Final opening debit<input aria-label="Final opening debit" type="number" min="0" step="0.01" className="input-field w-full" value={dr} onChange={e=>{invalidate();setDr(e.target.value);}}/></label><label>Final opening credit<input aria-label="Final opening credit" type="number" min="0" step="0.01" className="input-field w-full" value={cr} onChange={e=>{invalidate();setCr(e.target.value);}}/></label></div></div>}
   <button type="button" className="btn-primary" disabled={!ready||busy} onClick={()=>void inspect()}>{busy?'Working…':'Preview merge'}</button>
  </fieldset>
  {loading&&<p role="status">Loading masters…</p>}
  {preview&&<div className="border border-border rounded-lg p-4 space-y-4 min-w-0"><h3 className="font-semibold">Review → {preview.new_name}</h3>
   {!!preview.differences?.length&&<div className="space-y-3"><h4 className="font-semibold">Choose what to keep</h4><p className="text-sm text-muted-foreground">Select Source 1 or Source 2 for every differing block, then update the preview. Unselected values are kept in merge history, not in the active merged master.</p>{preview.differences.map((d:Row)=><fieldset key={d.key} disabled={busy} className="border border-border rounded-lg p-3 min-w-0"><legend className="text-sm font-semibold px-1">{d.label}</legend><div className="grid sm:grid-cols-2 gap-3">{(['a','b'] as const).map((side,index)=><label key={side} className={`border rounded-lg p-3 min-w-0 cursor-pointer ${choices[d.key]===side?'border-primary bg-primary/5':'border-border'}`}><span className="flex items-center gap-2 text-sm font-medium"><input type="radio" name={`merge-choice-${d.key}`} checked={choices[d.key]===side} onChange={()=>{setChoices(v=>({...v,[d.key]:side}));setChoicesDirty(true);setReviewed(false);setConfirm('');request.current='';}}/>Keep Source {index+1}</span><div className="mt-2 text-xs max-h-60 overflow-auto"><ChoiceValue value={d[side]}/></div></label>)}</div></fieldset>)}<button type="button" className="btn-secondary" disabled={busy||preview.differences.some((d:Row)=>!['a','b'].includes(choices[d.key]))} onClick={()=>void inspect()}>Update preview with my choices</button>{choicesDirty&&<p className="text-amber-800 text-sm" role="status">Choices changed. Update the preview before merging.</p>}</div>}
   <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="p-2 text-left">Detail</th><th className="p-2 text-left">Source 1</th><th className="p-2 text-left">Source 2</th><th className="p-2 text-left">After merge</th></tr></thead><tbody>{Array.from(new Set(['name','operator_name','item_name','style_no','operator_code','parent_group','gstin','department','process','set_type','op_bal_dr','op_bal_cr',...(preview.differences||[]).filter((d:Row)=>d.key.startsWith('field:')).map((d:Row)=>String(d.key).slice(6))])).filter(k=>[preview.source_a,preview.source_b,preview.target].some(r=>r[k]!=null&&r[k]!=='')).map(k=><tr key={k} className="border-t border-border"><td className="p-2">{k.replace(/_/g,' ')}</td>{[preview.source_a,preview.source_b,preview.target].map((r,i)=><td key={i} className="p-2 break-words">{String(r[k]??'—')}</td>)}</tr>)}</tbody></table></div>
   <h4 className="font-semibold">Linked entries to update</h4>{Object.entries(preview.impact||{}).map(([table,count])=><p key={table} className="text-sm break-words">{table.replace(/_/g,' ')}: {String(count)}</p>)}{!Object.keys(preview.impact||{}).length&&<p>No linked entries found.</p>}
   <details><summary>Source details and affected voucher references</summary><div className="max-h-80 overflow-auto text-xs space-y-2"><pre className="whitespace-pre-wrap break-all">{JSON.stringify({source1:preview.source_a,source2:preview.source_b,result:preview.target},null,2)}</pre>{(preview.changes||[]).map((r:Row,i:number)=><p key={i}>{r.table}: {r.before?.voucher_no||r.before?.entry_no||r.before?.issue_no||r.before?.job_card_no||r.id}{r.delete?' · Unselected duplicate detail archived':''}</p>)}</div></details>
   {(preview.warnings||[]).map((w:string)=><p key={w} className="text-amber-800 text-sm">{w}</p>)}
   {choicesDirty?<p className="text-sm">Review the updated result before confirming.</p>:!!preview.conflicts?.length?<div role="alert" className="text-red-700"><p className="font-semibold">Merge blocked. No records have changed.</p>{preview.conflicts.map((c:string)=><p key={c} className="text-sm break-words mt-2">{c}</p>)}<p className="text-sm mt-2">Do not remove voucher protections or delete valid entries to force a merge.</p></div>:<><label className="flex gap-2 text-sm"><input type="checkbox" disabled={busy} checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed both records, linked entries and the resulting details. Keep Source 1’s record identity, use my selected details and the reviewed final opening balances.</label><label className="block text-sm">Type the new name to confirm<input aria-label="Confirm merged name" className="input-field w-full" disabled={busy} value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button type="button" className="btn-primary" disabled={busy||!reviewed||confirm!==preview.new_name} onClick={()=>void merge()}>{busy?'Merging…':'Merge reviewed records'}</button></>}
  </div>}
  {error&&<p role="alert" className="text-red-700 break-words">{error}</p>}{notice&&<p role="status" className="text-green-700">{notice}</p>}
  </>}
 </section>;
}
