'use client';
import SearchableSelect from '@/components/SearchableSelect';

import {useEffect,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase/client';
import {useAuth} from '@/contexts/AuthContext';
import {erpErrorMessage} from '@/lib/erpError';
type JobRef={id:string;job_card_no:string};
export function ReceiptJobSelect({value,onChange,disabled=false}:{value:string[];onChange:(v:string[])=>void;disabled?:boolean}){
 const [jobs,setJobs]=useState<any[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let live=true;setBusy(true);setError('');void(async()=>{try{const rows:any[]=[];for(let offset=0;;offset+=200){const {data,error}=await supabase.rpc('erp_receipt_job_options',{p_offset:offset});if(error)throw error;rows.push(...data||[]);if(!data||data.length<200)break;}if(live)setJobs(rows);}catch(e){if(live)setError(erpErrorMessage(e));}finally{if(live)setBusy(false);}})();return()=>{live=false};},[retry]);
 const rows=value.length?value:[''];
 return <fieldset disabled={disabled||busy} className="border rounded-lg p-3 space-y-3"><legend className="text-sm font-semibold">Job Card reference (optional)</legend>{busy&&<p role="status">Loading Job Cards…</p>}{rows.map((id,index)=><div key={index} className="flex gap-2 items-center"><label className="flex-1 text-xs">Job Card {index+1}<SearchableSelect className="input-field w-full mt-1" value={id} disabled={!!error} onChange={e=>onChange(rows.map((v,i)=>i===index?e.target.value:v))}><option value="">Not linked / Select Job Card</option>{id&&!jobs.some(j=>j.id===id)&&<option value={id}>Current linked Job Card</option>}{jobs.map(j=><option key={j.id} value={j.id} disabled={j.id!==id&&rows.includes(j.id)}>{j.job_card_no} · {j.style_en||'—'} · {j.party_name||'—'}</option>)}</SearchableSelect></label>{rows.length>1&&<button type="button" className="text-red-600 text-sm" aria-label={`Remove Job Card ${index+1}`} onClick={()=>onChange(rows.filter((_,i)=>i!==index))}>Remove</button>}</div>)}<button type="button" className="text-primary underline text-sm" disabled={!!error||rows.some(id=>!id)||rows.length>=100} onClick={()=>onChange([...rows,''])}>+ Add another Job Card</button><p className="text-xs text-muted-foreground">Leave empty for general stock. Linking additional Job Cards does not multiply the received quantity.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}<button type="button" className="text-xs underline" onClick={()=>setRetry(v=>v+1)}>Reload Job Cards</button></fieldset>;

}
export default function ReceiptJobLink({receiptId,jobs,version,onSaved}:{receiptId:string;jobs:JobRef[];version:number;onSaved:()=>void}){
 const {can}=useAuth();const [editing,setEditing]=useState(false),[selected,setSelected]=useState(jobs.map(j=>j.id)),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <section className="border rounded-lg p-3 space-y-3"><p className="font-semibold">Linked Job Cards</p>{jobs.length?jobs.map(j=><p key={j.id}>{can('jobs')?<Link className="text-primary underline" href={`/production-batch/${j.id}`}>{j.job_card_no}</Link>:j.job_card_no}</p>):<p>Not linked / General stock</p>}{can('receive','edit')&&!editing&&<button type="button" className="text-primary underline" onClick={()=>{setSelected(jobs.map(j=>j.id));setEditing(true);}}>Link / Change Job Cards</button>}{editing&&<><ReceiptJobSelect value={selected} onChange={setSelected} disabled={busy}/><p className="text-xs text-muted-foreground">Reference only. Received stock is counted once, not once per Job Card.</p><button type="button" className="btn-primary" disabled={busy} onClick={async()=>{if(busy)return;setBusy(true);setError('');try{const r=await supabase.rpc('erp_link_receipt_jobs',{p_receipt_id:receiptId,p_job_card_ids:selected.filter(Boolean),p_version:version});if(r.error)throw r.error;window.dispatchEvent(new Event('erp-data-changed'));setEditing(false);onSaved();}catch(e){setError(erpErrorMessage(e));}finally{setBusy(false);}}}>{busy?'Saving…':'Save Job Card links'}</button><button type="button" className="btn-secondary ml-2" disabled={busy} onClick={()=>setEditing(false)}>Cancel</button></>}{error&&<p role="alert" className="text-red-700">{error}</p>}</section>;
}
