'use client';
import {useEffect,useRef,useState} from 'react';
import {supabase} from '@/lib/supabase/client';
import {erpErrorMessage} from '@/lib/erpError';
export const auditTime=(v:unknown)=>{if(!v)return 'Not recorded';const date=new Date(String(v));return Number.isNaN(date.getTime())?String(v):new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'medium',timeZone:'Asia/Kolkata'}).format(date)+' IST';};
export const fieldLabel=(v:string)=>v.replace(/([a-z])([A-Z])/g,'$1 $2').replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
type Event={id:string;created_at:string;performed_by:string;action:string;table_name:string;changes:Record<string,{before:unknown;after:unknown}>|null};
const value=(v:unknown)=>v===null||v===undefined?'—':typeof v==='object'?JSON.stringify(v):String(v);
export default function VoucherHistory({table,recordId}:{table:string;recordId:string}){
 const [open,setOpen]=useState(false),[rows,setRows]=useState<Event[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[more,setMore]=useState(false);const generation=useRef(0);
 useEffect(()=>{generation.current++;setOpen(false);setRows([]);setError('');setBusy(false);setMore(false);return()=>{generation.current++;};},[table,recordId]);
 async function load(next=false){const gen=generation.current;setBusy(true);setError('');try{const last=next?rows.at(-1):null;const {data,error}=await supabase.rpc('erp_entry_history',{p_table:table,p_record_id:recordId,p_before:last?.created_at||null,p_id:last?.id||null});if(error)throw error;if(gen!==generation.current)return;setRows(old=>next?[...old,...data]:data);setMore(data.length===50);}catch(e){if(gen===generation.current)setError(erpErrorMessage(e));}finally{if(gen===generation.current)setBusy(false);}}
 return <section className="text-xs border-t pt-3 mt-3"><button type="button" className="text-primary font-semibold" aria-expanded={open} onClick={()=>{setOpen(!open);if(!open)void load();}}>{open?'▾':'▸'} Entry history / बदलाव का इतिहास</button>{open&&<div className="mt-3 space-y-3 max-h-80 overflow-auto"><p className="text-muted-foreground">Every recorded edit · user, date and time (IST)</p>{error&&<div role="alert">{error} <button type="button" className="underline" disabled={busy} onClick={()=>void load()}>Retry</button></div>}{rows.map(row=><details key={row.id} className="border rounded-lg p-2"><summary className="cursor-pointer">{row.action==='INSERT'?'Created':row.action==='UPDATE'?'Edited':'Deleted'} · {row.performed_by||'User not recorded'} · {auditTime(row.created_at)}{row.table_name!==table?' · Component / line':''}</summary>{row.changes?<div className="overflow-x-auto"><table className="w-full text-left mt-2"><thead><tr><th>Field</th><th>Before</th><th>After</th></tr></thead><tbody>{Object.entries(row.changes).filter(([f])=>!['request_payload','id'].includes(f)).map(([field,change])=><tr key={field} className="border-t align-top"><td className="p-2">{fieldLabel(field)}</td><td className="p-2 break-words min-w-28">{value(change.before)}</td><td className="p-2 break-words min-w-28">{value(change.after)}</td></tr>)}</tbody></table></div>:<p>Detailed values were not recorded for this older event.</p>}</details>)}{busy&&<p role="status">Loading history…</p>}{!busy&&!rows.length&&!error&&<p>No history was recorded for this entry. Older changes cannot be reconstructed.</p>}{more&&<button type="button" className="underline" disabled={busy} onClick={()=>void load(true)}>Load older edits</button>}</div>}</section>;
}
