 'use client';
import {useState} from 'react';
import {usePathname} from 'next/navigation';
import {MODULES,moduleForRoute} from '@/lib/moduleAccess';
import {useAuth} from '@/contexts/AuthContext';
import {supabase} from '@/lib/supabase/client';
type Event={id:string;created_at:string;performed_by:string;action:string;table_name:string;record_id:string;changes:Record<string,{before:unknown;after:unknown}>|null;before_data:Record<string,unknown>|null;after_data:Record<string,unknown>|null};
const value=(v:unknown)=>v===null||v===undefined?'—':typeof v==='object'?JSON.stringify(v):String(v);
const when=(v:string)=>new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kolkata'}).format(new Date(v))+' IST';
export default function VoucherHistory(){const path=usePathname();const {can}=useAuth();const [open,setOpen]=useState(false),[rows,setRows]=useState<Event[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[more,setMore]=useState(false),[search,setSearch]=useState('');
const modules=MODULES.filter(([key,,route])=>(path===route||moduleForRoute(path)===key)&&can(key));const [chosen,setChosen]=useState('');const module=modules.find(([k])=>k===chosen)?.[0]||modules[0]?.[0];
if(!module)return null;
async function load(next=false,m=module){setBusy(true);setError('');try{const last=next?rows.at(-1):null;const {data,error}=await supabase.rpc('erp_module_history',{p_module:m,p_before:last?.created_at||null,p_id:last?.id||null});if(error)throw error;setRows(old=>next?[...old,...data]:data);setMore(data.length===50);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
return <div className="text-xs my-2"><button className="text-primary underline" onClick={()=>{setOpen(!open);if(!open)void load();}}>Entry history</button>{open&&<section className="border rounded-lg p-3 mt-2 space-y-3 max-h-96 overflow-auto"><div className="flex gap-2"><select aria-label="History module" value={module} onChange={e=>{setChosen(e.target.value);void load(false,e.target.value as typeof module);}}>{modules.map(([key,title])=><option value={key} key={key}>{title}</option>)}</select><input className="input-field" placeholder="Find voucher / user" value={search} onChange={e=>setSearch(e.target.value)}/></div><p>Every recorded change · times in IST. Older entries may not contain field-level history.</p>{error&&<p role="alert">{error}</p>}{rows.filter(row=>JSON.stringify(row).toLowerCase().includes(search.toLowerCase())).map(row=>{const d=row.after_data||row.before_data||{};const ref=d.voucher_no||d.entry_no||d.receipt_no||d.issue_no||d.dispatch_no||d.vch_no||d.job_card_no||d.purchase_no||row.record_id;return <details className="border-t py-2" key={row.id}><summary className="cursor-pointer">{String(ref)} · {row.action==='INSERT'?'Created':row.action==='UPDATE'?'Edited':'Deleted'} by {row.performed_by} · {when(row.created_at)}</summary>{row.changes?<table className="w-full mt-2 text-left"><thead><tr><th>Field</th><th>Before</th><th>After</th></tr></thead><tbody>{Object.entries(row.changes).map(([field,change])=><tr key={field} className="border-t"><td className="p-1">{field.replaceAll('_',' ')}</td><td className="p-1 break-all">{value(change.before)}</td><td className="p-1 break-all">{value(change.after)}</td></tr>)}</tbody></table>:<p>Detailed values were not recorded for this older event.</p>}</details>})}{!busy&&!rows.length&&!error&&<p>No recorded events yet.</p>}{busy&&<p>Loading…</p>}{more&&<button disabled={busy} className="underline" onClick={()=>void load(true)}>Load older events</button>}</section>}</div>}
