'use client';
import {useEffect,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
import {useAuth} from '@/contexts/AuthContext';
export default function DashboardSettings(){
 const {isAdmin}=useAuth();const [days,setDays]=useState(3),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{let alive=true;createClient().from('erp_dashboard_settings').select('inactivity_days').eq('id',1).single().then(({data,error})=>{if(!alive)return;setLoading(false);if(error)setError('Dashboard settings could not load. Apply DASHBOARD-SETTINGS.sql if this is the first installation.');else setDays(data.inactivity_days);});return()=>{alive=false;};},[]);
 async function save(){setSaving(true);setError('');setMessage('');try{const {error}=await createClient().rpc('erp_save_dashboard_settings',{p_days:days});if(error)throw error;setMessage('Saved for all users. Dashboards update on their next refresh.');window.dispatchEvent(new Event('erp-data-changed'));}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 return <section className="card-surface p-5"><h2 className="font-semibold">Dashboard status colours</h2><p className="text-sm text-muted-foreground my-2">Incomplete work turns red after this many days without voucher activity. Completed work stays green.</p><label className="flex gap-3 items-center">Inactivity days<input aria-label="Inactivity days" className="border rounded-lg p-2 w-24" type="number" min={1} max={30} step={1} value={days} disabled={loading||saving||!isAdmin} onChange={e=>setDays(Number(e.target.value))}/></label>{isAdmin&&<button onClick={()=>void save()} disabled={loading||saving||!Number.isInteger(days)||days<1||days>30} className="btn-primary mt-3">{saving?'Saving…':'Save for everyone'}</button>}{error&&<p role="alert" className="text-red-600 text-sm mt-3">{error}</p>}{message&&<p role="status" className="text-green-700 text-sm mt-3">{message}</p>}</section>;
}
